import test from "node:test";import assert from "node:assert/strict";import {initialState,switchWorkspace,canExecute,reconcile,injectScenario,visible} from "../src/domain.js";
test("mock dataset meets product floor",()=>{const s=initialState();assert.equal(s.workspaces.length,3);assert.ok(s.content.length>=12);assert.ok(s.tasks.length>=20);assert.ok(s.groups.length>=5);assert.ok(s.comments.length>=15);assert.ok(s.leads.length>=2)});
test("Agency view cannot execute",()=>{const s=initialState();const r=canExecute(s,s.tasks[0]);assert.equal(r.ok,false);assert.equal(r.code,"AGENCY_EXECUTION_BLOCKED")});
test("workspace isolation filters private records",()=>{const s=initialState();switchWorkspace(s,"ws-abc");assert.ok(visible(s,s.content).every(x=>x.workspaceId==="ws-abc"));assert.ok(visible(s,s.comments).every(x=>x.workspaceId==="ws-abc"))});
test("wrong workspace, identity and profile fail closed",()=>{for(const scenario of ["wrong_workspace","wrong_identity","wrong_profile"]){const s=initialState();switchWorkspace(s,"ws-vietbridge");const t=injectScenario(s,scenario);const r=canExecute(s,t);assert.equal(r.ok,false);assert.match(r.code,/WRONG_/);}});
test("revision or rule drift invalidates preflight",()=>{for(const scenario of ["rule_changed","content_changed"]){const s=initialState();switchWorkspace(s,"ws-vietbridge");const t=injectScenario(s,scenario);assert.equal(canExecute(s,t).code,"PREFLIGHT_INVALIDATED")}});
test("UNKNOWN is reconcile-first and has no retry",()=>{const s=initialState();switchWorkspace(s,"ws-vietbridge");const t=injectScenario(s,"submit_unknown");assert.equal(canExecute(s,t).code,"RECONCILE_FIRST");const out=reconcile(s,t.id,true);assert.equal(out.task.state,"PUBLISHED");assert.equal(s.audit[0].event,"RECONCILED")});
test("processing task blocks workspace switching",()=>{const s=initialState();switchWorkspace(s,"ws-vietbridge");s.tasks.find(t=>t.workspaceId==="ws-vietbridge").state="PROCESSING";assert.equal(switchWorkspace(s,"ws-abc").code,"ACTIVE_EXECUTION")});
test("content and execution use distinct states",()=>{const s=initialState();assert.ok(s.content.some(x=>x.status==="CONTENT_CHANGED"));assert.ok(s.tasks.some(x=>x.state==="RECONCILE_PENDING")===false);assert.ok(s.tasks.some(x=>x.state==="UNKNOWN"))});
