import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../src/store.js';

function setup(){const store=new Store(join(mkdtempSync(join(tmpdir(),'smo-quota-')),'db.sqlite')),workspace='ws-vietbridge',profile=store.saveProfile(workspace,{name:'FB',cdp_port:19421,user_data_dir:'/tmp/quota-profile'}),account=store.saveAccount(workspace,{display_name:'VB',profile_id:profile.id}),post=store.upsertPagePost(workspace,account.id,{id:'p1',permalink_url:'https://facebook.com/p1'});return {store,workspace,account,post};}

test('shadow mode classifies topics but cannot reserve an external reply',()=>{const {store,workspace,account,post}=setup();try{store.saveEngagementPolicy(workspace,{account_id:account.id,mode:'SHADOW',topics:'越南工厂，招聘',excluded:'广告，买卖'});store.upsertComments(workspace,post.id,[{external_id:'c1',author:'A',body:'越南工厂怎么改善排班？'},{external_id:'c2',author:'B',body:'越南工厂广告合作'},{external_id:'c3',author:'C',body:'越南工厂劳动法怎么处理？'}]);const rows=store.buildEngagementCandidates(workspace,account.id),low=rows.find(x=>x.state==='REPLY_CANDIDATE');assert.ok(low);assert.ok(rows.some(x=>x.state==='SKIP'));assert.ok(rows.some(x=>x.state==='HUMAN_REVIEW'));assert.throws(()=>store.reserveReplyQuota(workspace,low.id),/影子模式/);}finally{store.close();}});

test('auto low-risk mode reserves, counts and releases quota atomically',()=>{const {store,workspace,account,post}=setup();try{store.saveEngagementPolicy(workspace,{account_id:account.id,mode:'AUTO_LOW_RISK',topics:'越南工厂',daily_reply_limit:1,group_daily_limit:1,author_weekly_limit:1});store.upsertComments(workspace,post.id,[{external_id:'c1',author:'A',body:'越南工厂怎么改善排班？'}]);const candidate=store.buildEngagementCandidates(workspace,account.id)[0],reserved=store.reserveReplyQuota(workspace,candidate.id);assert.equal(reserved.reservation.state,'RESERVED');assert.equal(reserved.status.remaining,0);assert.throws(()=>store.reserveReplyQuota(workspace,candidate.id),/候选|额度/);const released=store.releaseQuota(workspace,reserved.reservation.id);assert.equal(released.remaining,1);assert.equal(store.facebookView(workspace).engagementCandidates[0].state,'REPLY_CANDIDATE');}finally{store.close();}});

test('configured limits cannot exceed hard safety ceilings',()=>{const {store,workspace,account}=setup();try{const p=store.saveEngagementPolicy(workspace,{account_id:account.id,mode:'AUTO_LOW_RISK',topics:'越南',daily_reply_limit:999,group_daily_limit:999,author_weekly_limit:999});assert.equal(p.daily_reply_limit,12);assert.equal(p.group_daily_limit,3);assert.equal(p.author_weekly_limit,2);}finally{store.close();}});

test('successful readback consumes quota while ambiguous submit keeps it locked',()=>{const one=setup();try{one.store.saveEngagementPolicy(one.workspace,{account_id:one.account.id,mode:'AUTO_LOW_RISK',topics:'越南工厂'});one.store.upsertComments(one.workspace,one.post.id,[{external_id:'c1',author:'A',body:'越南工厂怎么排班？'}]);let candidate=one.store.buildEngagementCandidates(one.workspace,one.account.id)[0],reserved=one.store.reserveReplyQuota(one.workspace,candidate.id);one.store.beginAutoReply(one.workspace,candidate.id,reserved.reservation.id);candidate=one.store.finishAutoReply(one.workspace,candidate.id,reserved.reservation.id,{reply_id:'r1'});assert.equal(candidate.state,'REPLIED');assert.equal(one.store.facebookView(one.workspace).quotaEvents[0].state,'CONSUMED');}finally{one.store.close()}const two=setup();try{two.store.saveEngagementPolicy(two.workspace,{account_id:two.account.id,mode:'AUTO_LOW_RISK',topics:'越南工厂'});two.store.upsertComments(two.workspace,two.post.id,[{external_id:'c2',author:'B',body:'越南工厂怎么排班？'}]);let candidate=two.store.buildEngagementCandidates(two.workspace,two.account.id)[0],reserved=two.store.reserveReplyQuota(two.workspace,candidate.id);two.store.beginAutoReply(two.workspace,candidate.id,reserved.reservation.id);candidate=two.store.markAutoReplyUnknown(two.workspace,candidate.id,reserved.reservation.id,'回读超时');assert.equal(candidate.state,'UNKNOWN');assert.equal(two.store.facebookView(two.workspace).quotaEvents[0].state,'RESERVED');}finally{two.store.close()}});

test('radar imports are idempotent and become topic candidates',()=>{const {store,workspace,account}=setup();try{const group=store.addGroup(workspace,{account_id:account.id,name:'白名单群组',url:'https://facebook.com/groups/123'});store.saveEngagementPolicy(workspace,{account_id:account.id,mode:'SHADOW',topics:'越南工厂'});const item={group_id:group.id,external_id:'post-1',permalink:'https://facebook.com/groups/123/posts/post-1/',author:'Alice',body:'越南工厂怎么改善排班？',topic:'越南工厂'};store.ingestRadarPosts(workspace,account.id,[item]);store.ingestRadarPosts(workspace,account.id,[item]);assert.equal(store.facebookView(workspace).radarPosts.length,1);assert.ok(store.buildEngagementCandidates(workspace,account.id).some(x=>x.state==='REPLY_CANDIDATE'));}finally{store.close();}});
