import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../src/store.js';

function setup(){const store=new Store(join(mkdtempSync(join(tmpdir(),'smo-fb-')),'db.sqlite')),workspace='ws-vietbridge';const profile=store.saveProfile(workspace,{name:'FB test',cdp_port:19123,user_data_dir:'/tmp/fb-test-profile'});const account=store.saveAccount(workspace,{display_name:'VietBridge',expected_identity:'VietBridge',identity_type:'PROFILE',profile_id:profile.id});return {store,workspace,profile,account};}

test('tenant account CRUD and execution profile mapping fail closed',()=>{const {store,workspace,account}=setup();try{assert.equal(store.facebookView(workspace).accounts[0].profile_id,account.profile_id);assert.throws(()=>store.saveAccount('ws-abc',{...account,id:account.id}),/不属于|不存在/);assert.throws(()=>store.saveAccount(workspace,{display_name:'x',expected_identity:'x',profile_id:'missing'}),/执行环境/);}finally{store.close();}});

test('group sync dedupes, marks stale and manual add remains available',()=>{const {store,workspace,account}=setup();try{let groups=store.syncGroups(workspace,account.id,[{name:'A',url:'https://www.facebook.com/groups/123/'},{name:'A duplicate',url:'https://www.facebook.com/groups/123'}]);assert.equal(groups.length,1);groups=store.syncGroups(workspace,account.id,[{name:'B',url:'https://www.facebook.com/groups/456'}]);assert.equal(groups.find(x=>x.external_id==='123').membership_status,'STALE');assert.equal(groups.find(x=>x.external_id==='456').membership_status,'JOINED');store.addGroup(workspace,{account_id:account.id,name:'Manual',url:'https://facebook.com/groups/manual'});assert.equal(store.facebookView(workspace).facebookGroups.length,3);}finally{store.close();}});

test('one content creates independent jobs and wrong identity is blocked before insertion',()=>{const {store,workspace,account}=setup();try{const g1=store.addGroup(workspace,{account_id:account.id,name:'一群',url:'https://facebook.com/groups/100'}),g2=store.addGroup(workspace,{account_id:account.id,name:'二群',url:'https://facebook.com/groups/200'}),content=store.createContent(workspace,{title:'中文',body:'完整中文正文',media:[]}),jobs=store.createGroupJobs(workspace,{account_id:account.id,content_id:content.id,group_ids:[g1.id,g2.id]});assert.equal(jobs.length,2);assert.notEqual(jobs[0].id,jobs[1].id);assert.throws(()=>store.beginPrepare(workspace,jobs[0].id,'Wrong identity'),/身份/);assert.equal(store.job(workspace,jobs[0].id).state,'PENDING');const prepared=store.beginPrepare(workspace,jobs[0].id,'VietBridge');assert.equal(prepared.state,'PREPARING');store.finishPrepare(workspace,prepared.id,{text_verified:true});store.markUnknown(workspace,prepared.id,'forced uncertainty');assert.equal(store.job(workspace,prepared.id).state,'UNKNOWN');assert.throws(()=>store.beginPrepare(workspace,prepared.id,'VietBridge'),/不能重新准备/);}finally{store.close();}});

test('post claims, comments dedupe and duplicate replies are prevented across restart',()=>{const {store,workspace,account}=setup();const path=store.db.prepare('PRAGMA database_list').get().file;let reopened;try{const group=store.addGroup(workspace,{account_id:account.id,name:'A',url:'https://facebook.com/groups/123'}),content=store.createContent(workspace,{body:'hello',media:[]}),job=store.createGroupJobs(workspace,{account_id:account.id,content_id:content.id,group_ids:[group.id]})[0];store.beginPrepare(workspace,job.id,'VietBridge');store.finishPrepare(workspace,job.id,{});const published=store.claimPost(workspace,job.id,'https://www.facebook.com/groups/123/posts/999/'),post=store.facebookView(workspace).publishedPosts[0];assert.equal(published.state,'PUBLISHED');store.upsertComments(workspace,post.id,[{external_id:'c1',author:'Alice',body:'你好'}]);store.upsertComments(workspace,post.id,[{external_id:'c1',author:'Alice',body:'你好'}]);const comment=store.facebookView(workspace).facebookComments[0];assert.equal(store.facebookView(workspace).facebookComments.length,1);store.createReplyIntent(workspace,comment.id,'谢谢');assert.throws(()=>store.createReplyIntent(workspace,comment.id,'谢谢'),/重复/);store.close();reopened=new Store(path);assert.equal(reopened.facebookView(workspace).groupJobs[0].state,'PUBLISHED');assert.equal(reopened.facebookView(workspace).replyIntents.length,1);}finally{try{store.close()}catch{}reopened?.close();}});
