import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {Store} from '../src/store.js';

function setup(){const store=new Store(join(mkdtempSync(join(tmpdir(),'smo-fb-')),'db.sqlite')),workspace='ws-vietbridge';const profile=store.saveProfile(workspace,{name:'FB test',cdp_port:19123,user_data_dir:'/tmp/fb-test-profile'});const account=store.saveAccount(workspace,{display_name:'VietBridge',expected_identity:'VietBridge',identity_type:'PROFILE',profile_id:profile.id});return {store,workspace,profile,account};}

test('tenant account CRUD and execution profile mapping fail closed',()=>{const {store,workspace,account}=setup();try{assert.equal(store.facebookView(workspace).accounts[0].profile_id,account.profile_id);assert.throws(()=>store.saveAccount('ws-abc',{...account,id:account.id}),/不属于|不存在/);assert.throws(()=>store.saveAccount(workspace,{display_name:'x',expected_identity:'x',profile_id:'missing'}),/执行环境/);}finally{store.close();}});
test('profile directory rejects Drive URLs and keeps tenant profiles separate',()=>{const {store,workspace,profile}=setup();try{assert.throws(()=>store.saveProfile(workspace,{id:profile.id,name:'broken',cdp_port:19123,user_data_dir:'https://drive.google.com/drive/folders/abc'}),/本机专用绝对路径/);assert.throws(()=>store.saveProfile(workspace,{id:profile.id,name:'broken',cdp_port:19123,user_data_dir:'/Users/test/Library/CloudStorage/GoogleDrive/My Drive/profile'}),/本机专用绝对路径/);const updated=store.saveProfile(workspace,{id:profile.id,name:'LP visa',cdp_port:19123,user_data_dir:'/tmp/lp-visa-profile'});assert.equal(updated.id,profile.id);assert.equal(updated.user_data_dir,'/tmp/lp-visa-profile');assert.throws(()=>store.saveProfile('ws-abc',{name:'other',cdp_port:19123,user_data_dir:'/tmp/other-profile'}),/端口或浏览器数据目录/);}finally{store.close();}});
test('selected account persists per workspace and editable local config URLs stay isolated',()=>{const {store,workspace,profile,account}=setup();try{const second=store.saveAccount(workspace,{display_name:'Second',expected_identity:'Second',external_id:'2002',profile_id:profile.id,config_url:'file:///tmp/second.env'});store.selectAccount(workspace,second.id);assert.equal(store.facebookView(workspace).selectedAccountId,second.id);store.saveAccount(workspace,{id:second.id,display_name:'Second edited',expected_identity:'Second',profile_id:profile.id,config_url:'/tmp/edited.env'});assert.equal(store.account(workspace,second.id).config_url,'/tmp/edited.env');assert.equal(store.account(workspace,second.id).external_id,'2002');assert.equal(store.account(workspace,account.id).display_name,'VietBridge');assert.throws(()=>store.saveAccount(workspace,{...second,external_id:'not-a-page',config_url:'/tmp/edited.env'}),/Page ID/);assert.throws(()=>store.saveAccount(workspace,{...second,config_url:'https://example.com/secret.env'}),/本地文件/);assert.throws(()=>store.saveAccount(workspace,{...second,config_url:'/tmp/account.env.rtf'}),/富文本/);}finally{store.close();}});

test('group sync dedupes, marks stale and manual add remains available',()=>{const {store,workspace,account}=setup();try{let groups=store.syncGroups(workspace,account.id,[{name:'A',url:'https://www.facebook.com/groups/123/'},{name:'A duplicate',url:'https://www.facebook.com/groups/123'}]);assert.equal(groups.length,1);groups=store.syncGroups(workspace,account.id,[{name:'B',url:'https://www.facebook.com/groups/456'}]);assert.equal(groups.find(x=>x.external_id==='123').membership_status,'STALE');assert.equal(groups.find(x=>x.external_id==='456').membership_status,'JOINED');store.addGroup(workspace,{account_id:account.id,name:'Manual',url:'https://facebook.com/groups/manual'});assert.equal(store.facebookView(workspace).facebookGroups.length,3);}finally{store.close();}});

test('one content creates independent jobs and wrong identity is blocked before insertion',()=>{const {store,workspace,account}=setup();try{const g1=store.addGroup(workspace,{account_id:account.id,name:'一群',url:'https://facebook.com/groups/100'}),g2=store.addGroup(workspace,{account_id:account.id,name:'二群',url:'https://facebook.com/groups/200'}),content=store.createContent(workspace,{title:'中文',body:'完整中文正文',media:[]}),jobs=store.createGroupJobs(workspace,{account_id:account.id,content_id:content.id,group_ids:[g1.id,g2.id]});assert.equal(jobs.length,2);assert.notEqual(jobs[0].id,jobs[1].id);assert.throws(()=>store.beginPrepare(workspace,jobs[0].id,'Wrong identity'),/身份/);assert.equal(store.job(workspace,jobs[0].id).state,'PENDING');const prepared=store.beginPrepare(workspace,jobs[0].id,'VietBridge');assert.equal(prepared.state,'PREPARING');store.finishPrepare(workspace,prepared.id,{text_verified:true});store.markUnknown(workspace,prepared.id,'forced uncertainty');assert.equal(store.job(workspace,prepared.id).state,'UNKNOWN');assert.throws(()=>store.beginPrepare(workspace,prepared.id,'VietBridge'),/不能重新准备/);}finally{store.close();}});

test('automatic submit commits intent and form snapshot before processing',()=>{const {store,workspace,account}=setup();try{const group=store.addGroup(workspace,{account_id:account.id,name:'A',url:'https://facebook.com/groups/123'}),content=store.createContent(workspace,{body:'hello',media:[]}),job=store.createGroupJobs(workspace,{account_id:account.id,content_id:content.id,group_ids:[group.id]})[0];store.beginPrepare(workspace,job.id,'VietBridge');store.finishPrepare(workspace,job.id,{text_verified:true});const processing=store.beginSubmit(workspace,job.id,{target_url:group.url});assert.equal(processing.state,'PROCESSING');assert.equal(store.db.prepare('SELECT count(*) n FROM publication_intents WHERE job_id=?').get(job.id).n,1);assert.equal(store.db.prepare('SELECT body FROM form_snapshots WHERE job_id=?').get(job.id).body,'hello');assert.throws(()=>store.beginSubmit(workspace,job.id,{}),/尚未完成/);store.markUnknown(workspace,job.id,'ambiguous');assert.equal(store.job(workspace,job.id).state,'UNKNOWN');}finally{store.close();}});

test('post claims, comments dedupe and duplicate replies are prevented across restart',()=>{const {store,workspace,account}=setup();const path=store.db.prepare('PRAGMA database_list').get().file;let reopened;try{const group=store.addGroup(workspace,{account_id:account.id,name:'A',url:'https://facebook.com/groups/123'}),content=store.createContent(workspace,{body:'hello',media:[]}),job=store.createGroupJobs(workspace,{account_id:account.id,content_id:content.id,group_ids:[group.id]})[0];store.beginPrepare(workspace,job.id,'VietBridge');store.finishPrepare(workspace,job.id,{});assert.throws(()=>store.claimPost(workspace,job.id,'https://www.facebook.com/groups/123/posts/999/'),/独立回读/);const published=store.claimPost(workspace,job.id,'https://www.facebook.com/groups/123/posts/999/',{method:'MANUAL_POST_BROWSER_READBACK',checked_at:new Date().toISOString()}),post=store.facebookView(workspace).publishedPosts[0];assert.equal(published.state,'PUBLISHED');store.upsertComments(workspace,post.id,[{external_id:'c1',author:'Alice',body:'你好'}]);store.upsertComments(workspace,post.id,[{external_id:'c1',author:'Alice',body:'你好'}]);const comment=store.facebookView(workspace).facebookComments[0];assert.equal(store.facebookView(workspace).facebookComments.length,1);store.createReplyIntent(workspace,comment.id,'谢谢');assert.throws(()=>store.createReplyIntent(workspace,comment.id,'谢谢'),/重复/);store.close();reopened=new Store(path);assert.equal(reopened.facebookView(workspace).groupJobs[0].state,'PUBLISHED');assert.equal(reopened.facebookView(workspace).replyIntents.length,1);}finally{try{store.close()}catch{}reopened?.close();}});

test('Page feed import is idempotent and reply preflight never marks sent',()=>{const {store,workspace,account}=setup();try{const item={id:'page_123',permalink_url:'https://www.facebook.com/123'};const first=store.upsertPagePost(workspace,account.id,item),second=store.upsertPagePost(workspace,account.id,item);assert.equal(first.id,second.id);store.upsertComments(workspace,first.id,[{external_id:'comment_1',author:'Alice',body:'请问怎么处理？'}]);const comment=store.facebookView(workspace).facebookComments[0],intent=store.createReplyIntent(workspace,comment.id,'建议先核对具体情况。'),checked=store.markReplyPreflight(workspace,intent.id,{dry_run:true,would_send:true});assert.equal(checked.state,'READY_FOR_APPROVAL');assert.notEqual(checked.state,'SENT');assert.equal(store.facebookView(workspace).publishedPosts.length,1);}finally{store.close();}});
