import {QA_CASES} from "./qa-cases.js";
const routes=[['today','今日'],['content','内容'],['distribution','分发'],['publish','发布'],['community','社群'],['engagement','互动'],['data','数据'],['clients','客户'],['system','系统']];let state,message=null;
async function api(path,body){const r=await fetch(path,{method:body?'POST':'GET',headers:body?{'content-type':'application/json'}:{},body:body?JSON.stringify(body):undefined});const data=await r.json();if(!r.ok)throw Object.assign(Error(data.message||data.error||'操作失败'),{data});return data}
async function load(){state=await api('/api/state');render()}
function workspace(){return state.workspaces.find(w=>w.id===state.workspaceId)}
function scoped(list){return state.mode==='agency'?list:list.filter(x=>x.workspaceId===state.workspaceId)}
function status(s){const bad=['UNKNOWN','NEEDS_REVIEW','CONTENT_CHANGED','RULES_CHANGED','UNASSIGNED'].includes(s);return `<span class="status ${bad?'bad':'good'}">${label(s)}</span>`}
function label(s){return ({READY:'可执行',PROCESSING:'处理中',PUBLISHED:'已发布',UNKNOWN:'结果待核对',NEEDS_REVIEW:'需要处理',CONTENT_CHANGED:'内容已变化',RULES_CHANGED:'规则已变化',UNASSIGNED:'待分配',COMPOSER_READY:'等待人工最终点击',DISCOVERED:'待分类',HUMAN_HANDOFF:'人工接管'}[s]||s)}
function shell(content){const w=workspace();return `<div class="shell"><aside class="side"><div class="brand">VietBridge<small>SOCIAL OPERATOR V2</small></div><nav class="nav">${routes.map(([id,n])=>`<button data-route="${id}" class="${state.route===id?'active':''}">${n}</button>`).join('')}</nav></aside><main class="main"><header class="top"><div><h1>${state.mode==='agency'?'Agency Operations':w?.name||'Workspace'}</h1><div class="muted">${state.mode==='agency'?'跨客户监控与调度，不允许执行发布或回复':`${w.brand} · ${w.project}`}</div></div><div class="context"><button class="btn" data-agency>Agency</button><select data-workspace><option value="">进入客户…</option>${state.workspaces.map(x=>`<option value="${x.id}" ${x.id===state.workspaceId?'selected':''}>${x.name}</option>`).join('')}</select>${w?`<span class="status ${w.health==='正常'?'good':'bad'}">账号${w.health}</span>`:''}</div></header>${message?`<div class="notice ${message.error?'error':''}"><strong>${message.title}</strong><div>${message.text}</div></div>`:''}${content}</main></div>`}
function dashboard(){const tasks=scoped(state.tasks),contents=scoped(state.content),comments=scoped(state.comments);return `<div class="grid"><div class="metric">可分发内容<strong>${contents.filter(x=>x.status==='READY').length}</strong></div><div class="metric">需要处理<strong>${tasks.filter(x=>['UNKNOWN','NEEDS_REVIEW'].includes(x.state)).length}</strong></div><div class="metric">互动待办<strong>${comments.filter(x=>x.state==='DISCOVERED').length}</strong></div><div class="metric">潜在线索<strong>${scoped(state.leads).length}</strong></div></div><section class="panel"><div class="panelhead"><h2>当前任务</h2><span class="pill">${state.mode==='agency'?'全部客户':'仅当前客户'}</span></div>${taskTable(tasks.slice(0,8))}</section>`}
function taskTable(tasks){return `<div class="tablewrap"><table><thead><tr><th>客户</th><th>内容</th><th>平台</th><th>状态</th><th>说明</th><th>动作</th></tr></thead><tbody>${tasks.map(t=>{const w=state.workspaces.find(x=>x.id===t.workspaceId),c=state.content.find(x=>x.id===t.contentId);return `<tr class="taskrow ${t.state==='UNKNOWN'?'block':''}"><td>${w?.name}</td><td>${c?.title}</td><td>${t.platform}</td><td>${status(t.state)}</td><td>${t.reason||'—'}</td><td><div class="actions">${t.state==='UNKNOWN'?`<button class="btn" data-reconcile="${t.id}">先对账</button>`:`<button class="btn primary" data-exec="${t.id}">准备执行</button>`}</div></td></tr>`}).join('')}</tbody></table></div>`}
function contentPage(){const items=scoped(state.content);return `<section class="panel"><div class="panelhead"><h2>内容与版本</h2><span class="pill">Revision / Hash 绑定</span></div><div class="cards">${items.map(c=>`<article class="card"><h3>${c.title}</h3><div class="muted">${c.id} · ${c.revision}</div><p>${status(c.status)}</p><div class="muted">训练价值 ${c.trainingValue}/12 · 社媒入口 ${c.socialValue}/12</div><div class="muted">${c.variants.join(' · ')}</div></article>`).join('')}</div></section>`}
function distribution(){return `<section class="panel"><div class="panelhead"><h2>Content Distribution Hub</h2><span class="pill">同一事实核心，多平台版本</span></div>${taskTable(scoped(state.tasks))}</section>`}
function community(){return `<section class="panel"><div class="panelhead"><h2>Facebook Community — WHAT / WHO / ENGAGE</h2><span class="pill">Human final click</span></div><div class="cards">${scoped(state.groups).map(g=>`<article class="card"><h3>${g.name}</h3><div class="muted">${g.language} · 冷却 ${g.cooling}</div><p>匹配度 <strong>${g.match}</strong></p><div class="actions"><button class="btn">查看规则</button><button class="btn">创建 Group Variant</button></div></article>`).join('')||'<div class="empty">当前客户没有已配置社群</div>'}</div></section>`}
function engagement(){return `<section class="panel"><div class="panelhead"><h2>互动 Inbox</h2><span class="pill">回复也是独立 EngagementTask</span></div><div class="cards">${scoped(state.comments).map(c=>`<article class="card"><h3>${c.author}</h3><p>${c.text}</p><div>${status(c.state)} <span class="pill">${c.intent}</span></div><div class="actions"><button class="btn primary">准备回复</button><button class="btn">忽略</button></div></article>`).join('')}</div></section>`}
function system(){const scenarios=[['wrong_workspace','Wrong Workspace'],['wrong_identity','Wrong Identity'],['wrong_profile','Wrong Profile'],['chrome_disconnected','Chrome 断开'],['partial_text','中文残缺'],['media_failed','媒体失败'],['submit_unknown','Submit UNKNOWN'],['video_processing','视频处理'],['rule_changed','规则变化'],['content_changed','内容变化'],['token_expired','授权失效']];return `<section class="panel"><div class="panelhead"><h2>Dev / QA 故障模拟器</h2><button class="btn" data-reset>重置 Mock</button></div><p class="muted">只改变内存 Mock 状态，不连接任何真实平台。</p><div class="scenario">${scenarios.map(([id,n])=>`<button class="btn" data-scenario="${id}">${n}</button>`).join('')}</div></section><section class="panel"><div class="panelhead"><h2>UC-001—UC-056 验收映射</h2><span class="pill">${QA_CASES.length} cases</span></div><div class="tablewrap"><table><thead><tr><th>ID</th><th>场景</th><th>覆盖</th></tr></thead><tbody>${QA_CASES.map(q=>`<tr><td>${q.id}</td><td>${q.title}</td><td>${q.coverage==='AUTOMATED'?status('PUBLISHED'):'可点击 Mock'}</td></tr>`).join('')}</tbody></table></div></section>`}
function render(){let content=state.route==='today'?dashboard():state.route==='content'?contentPage():['distribution','publish'].includes(state.route)?distribution():state.route==='community'?community():state.route==='engagement'?engagement():state.route==='system'?system():dashboard();document.querySelector('#app').innerHTML=shell(content);bind()}
function bind(){document.querySelectorAll('[data-route]').forEach(b=>b.onclick=async()=>{state=(await api('/api/route',{route:b.dataset.route})).state;message=null;render()});document.querySelector('[data-agency]').onclick=async()=>{state=(await api('/api/context',{mode:'agency'})).state;message=null;render()};document.querySelector('[data-workspace]').onchange=async e=>{if(!e.target.value)return;try{state=(await api('/api/context',{mode:'workspace',workspaceId:e.target.value})).state;message=null}catch(err){state=err.data.state;message={error:true,title:'不能切换客户',text:err.message}}render()};document.querySelectorAll('[data-exec]').forEach(b=>b.onclick=async()=>{try{const x=await api(`/api/tasks/${b.dataset.exec}/execute`,{});state=x.state;message={title:'已准备',text:x.task.reason}}catch(err){state=err.data.state;message={error:true,title:err.data.code||'已阻止',text:err.message}}render()});document.querySelectorAll('[data-reconcile]').forEach(b=>b.onclick=async()=>{const x=await api(`/api/tasks/${b.dataset.reconcile}/reconcile`,{found:true});state=x.state;message={title:'对账完成',text:x.task.reason};render()});document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=async()=>{const x=await api('/api/scenario',{scenario:b.dataset.scenario});state=x.state;message={error:true,title:'已注入故障',text:x.task.reason||b.textContent};render()});const reset=document.querySelector('[data-reset]');if(reset)reset.onclick=async()=>{state=await api('/api/reset',{});message=null;render()}}
load();
