import {spawn} from 'node:child_process';
import {request} from 'node:http';

const CHROME='/Applications/Google Chrome.app/Contents/MacOS/Google Chrome';
export class FacebookBrowser {
  constructor(store){this.store=store;this.processes=new Map();}
  async launch(workspace,profileId){const p=this.profile(workspace,profileId);if(await cdpReady(p.cdp_port))return {status:'READY',cdp_port:p.cdp_port};const child=spawn(CHROME,[`--remote-debugging-port=${p.cdp_port}`,`--user-data-dir=${p.user_data_dir}`,'--no-first-run','https://www.facebook.com/groups/joins/'],{detached:true,stdio:'ignore'});child.unref();this.processes.set(profileId,child.pid);for(let i=0;i<30;i++){await new Promise(r=>setTimeout(r,250));if(await cdpReady(p.cdp_port)){this.store.db.prepare("UPDATE execution_profiles SET status='READY',last_error=NULL WHERE id=?").run(profileId);return {status:'READY',cdp_port:p.cdp_port};}}this.store.db.prepare("UPDATE execution_profiles SET status='BLOCKED',last_error='Chrome CDP 未就绪' WHERE id=?").run(profileId);throw new Error('Chrome 未能启动；请检查执行环境或手动关闭同目录的 Chrome');}
  async inspect(workspace,accountId){const account=this.store.account(workspace,accountId),profile=this.profile(workspace,account.profile_id);const {browser,page}=await this.page(profile);try{await page.goto('https://www.facebook.com/me',{waitUntil:'domcontentloaded',timeout:45000});const url=page.url(),title=await page.title(),body=await page.locator('body').innerText().catch(()=>'');if(await page.locator('input[name="email"],input[name="pass"]').count()||/login|checkpoint/i.test(url)||/Log in to Facebook|登录 Facebook/i.test(body)){this.health(account.id,'LOGIN_REQUIRED',false);return {healthy:false,actualIdentity:null,url,title,blocker:'FACEBOOK_LOGIN_REQUIRED'};}const identity=normalize(await page.locator('h1').first().textContent({timeout:8000}).catch(()=>''));if(!identity||identity==='Facebook'){this.health(account.id,'IDENTITY_UNVERIFIED',false);return {healthy:false,actualIdentity:null,url,title,blocker:'FACEBOOK_IDENTITY_NOT_OBSERVABLE'};}const matches=identity===account.expected_identity;this.health(account.id,matches?'HEALTHY':'WRONG_IDENTITY',matches);return {healthy:matches,actualIdentity:identity,url,title,blocker:matches?null:'WRONG_IDENTITY'};}finally{await browser.close();}}
  async discoverGroups(workspace,accountId){const account=this.store.account(workspace,accountId),profile=this.profile(workspace,account.profile_id);const checked=await this.inspect(workspace,accountId);if(!checked.healthy)throw new Error('Facebook 登录已失效，请先在此执行环境登录');if(checked.actualIdentity!==account.expected_identity)throw new Error(`实际 Facebook 身份“${checked.actualIdentity}”与预期“${account.expected_identity}”不一致`);const {browser,page}=await this.page(profile);try{await page.goto('https://www.facebook.com/groups/joins/',{waitUntil:'domcontentloaded',timeout:45000});for(let i=0;i<8;i++){await page.mouse.wheel(0,1600);await page.waitForTimeout(350);}const groups=await page.locator('a[href*="/groups/"]').evaluateAll(links=>{const seen=new Set();return links.map(a=>({name:(a.textContent||'').trim().replace(/\s+/g,' '),url:a.href.split('?')[0].replace(/\/$/,'')})).filter(x=>x.name&&/^https:\/\/(www\.)?facebook\.com\/groups\/[^/]+/.test(x.url)&&!seen.has(x.url)&&seen.add(x.url));});if(!groups.length)throw new Error('未能从 Facebook“你的群组”页面识别群组；可先使用手工添加群组链接');return {identity:checked.actualIdentity,groups};}finally{await browser.close();}}
  async prepareJob(workspace,jobId){const job=this.store.job(workspace,jobId),account=this.store.account(workspace,job.account_id),profile=this.profile(workspace,job.profile_id),group=this.store.db.prepare('SELECT * FROM facebook_groups WHERE id=?').get(job.group_id),content=this.store.db.prepare('SELECT * FROM group_content WHERE id=?').get(job.content_id);const checked=await this.inspect(workspace,account.id);this.store.beginPrepare(workspace,job.id,checked.actualIdentity);const {browser,page}=await this.page(profile);try{await page.goto(group.url,{waitUntil:'domcontentloaded',timeout:45000});if(!page.url().includes(new URL(group.url).pathname))throw new Error('Facebook 未停留在目标群组，已阻止写入');const composer=page.getByRole('button',{name:/写点什么|Write something/i}).first();await composer.click({timeout:15000});const box=page.getByRole('textbox').last();await box.fill(content.body);const actual=await box.textContent();if(normalize(actual)!==normalize(content.body))throw new Error('正文完整性核对失败，已阻止提交');const media=JSON.parse(content.media_json);if(media.length){const input=page.locator('input[type=file]').last();await input.setInputFiles(media);await page.waitForTimeout(1000);if(await input.count()===0)throw new Error('未找到媒体附件入口');}const evidence={target_url:page.url(),group_name:group.name,actual_identity:checked.actualIdentity,text_hash:content.content_hash,media_count:media.length,prepared_at:new Date().toISOString(),human_final_click_required:true};this.store.finishPrepare(workspace,job.id,evidence);return evidence;}catch(error){this.store.markUnknown(workspace,job.id,String(error));throw error;}finally{await browser.close();}}
  health(accountId,status,verified){this.store.db.prepare('UPDATE facebook_accounts SET session_health=?,identity_verified_at=? WHERE id=?').run(status,verified?new Date().toISOString():null,accountId);}
  profile(workspace,id){return this.store.db.prepare('SELECT * FROM execution_profiles WHERE id=? AND workspace=?').get(id,workspace)||(()=>{throw new Error('执行环境不存在')})();}
  async page(profile){if(!await cdpReady(profile.cdp_port))throw new Error('执行环境未连接，请先启动 Chrome');const {chromium}=await import('playwright-core');const browser=await chromium.connectOverCDP(`http://127.0.0.1:${profile.cdp_port}`);const context=browser.contexts()[0];const page=context.pages()[0]||await context.newPage();return {browser,page};}
}
function normalize(x){return String(x||'').replace(/\s+/g,' ').trim();}
function cdpReady(port){return new Promise(resolve=>{const req=request({host:'127.0.0.1',port,path:'/json/version',timeout:500},res=>{res.resume();resolve(res.statusCode===200)});req.on('error',()=>resolve(false));req.on('timeout',()=>{req.destroy();resolve(false)});req.end();});}
