import {randomBytes,scryptSync,timingSafeEqual,createHash} from 'node:crypto';
import {existsSync,readFileSync,writeFileSync,renameSync,statSync,mkdirSync} from 'node:fs';
import {dirname,join} from 'node:path';
const hash=s=>createHash('sha256').update(s).digest('hex');
export function passwordRecord(password){if(typeof password!=='string'||password.length<6||password.length>512)throw Error('密码需要6至512个字符');const salt=randomBytes(16).toString('hex');return {salt,hash:scryptSync(password,salt,64).toString('hex')};}
export function passwordMatches(password,record){if(typeof password!=='string'||password.length>512||!record||! /^[a-f0-9]{32}$/.test(record.salt||'')||! /^[a-f0-9]{128}$/.test(record.hash||''))return false;return timingSafeEqual(scryptSync(password,record.salt,64),Buffer.from(record.hash,'hex'));}
export function readAccessFile(path){if(!existsSync(path))return null;const info=statSync(path);if(!info.isFile()||(info.mode&0o077))throw Error('登录配置必须是已有私有文件');const value=JSON.parse(readFileSync(path,'utf8'));if(value.version!==1||!value.user||! /^[a-f0-9]{128}$/.test(value.password?.hash||'')||! /^[a-f0-9]{32}$/.test(value.password?.salt||'')||!Array.isArray(value.tokens))throw Error('登录配置格式无效');return value;}
export function writeAccessFile(path,value){mkdirSync(dirname(path),{recursive:true});const temp=join(dirname(path),'.publisher-access-'+randomBytes(16).toString('hex'));writeFileSync(temp,JSON.stringify(value),{mode:0o600,flag:'wx'});renameSync(temp,path);}
const scopes=['jobs:read','content:import','jobs:create'];
export class PublisherAccess {
 constructor(config,{now=()=>Date.now()}={}){this.config=config;this.now=now;this.file=config.accessFile;this.data=this.file?readAccessFile(this.file):null;this.data||={version:1,user:config.user,password:passwordRecord(config.password),tokens:[]};this.sessions=new Map();this.basicCache=new Map();this.attempts=[];}
 persist(){if(!this.file)throw Error('未配置持久登录文件');writeAccessFile(this.file,this.data);}
 validPassword(user,password){return user===this.data.user&&passwordMatches(password,this.data.password);}
 login(user,password){this.attempts=this.attempts.filter(t=>t>this.now()-60000);if(this.attempts.length>=10)throw Error('登录过于频繁，请稍后重试');this.attempts.push(this.now());if(!this.validPassword(user,password))throw Error('用户名或密码不正确');if(this.sessions.size>=500){for(const [key,value] of this.sessions)if(value.expires<=this.now())this.sessions.delete(key);if(this.sessions.size>=500)throw Error('会话数量已满，请稍后登录');}const secret=randomBytes(32).toString('base64url');this.sessions.set(hash(secret),{expires:this.now()+12*3600000});return secret;}
 authenticate(req){const header=req.headers.authorization||'';if(header.startsWith('Bearer ')){const t=this.data.tokens.find(x=>x.hash===hash(header.slice(7))&&!x.revoked&&x.expires>this.now());return t?{type:'app',token:t}:null;}
 const value=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('publisher_session='))?.slice(18);const session=value&&this.sessions.get(hash(value));if(session&&session.expires>this.now())return {type:'admin'};
 if(header.startsWith('Basic ')){const key=hash(header),cached=this.basicCache.get(key);if(cached&&cached>this.now())return {type:'admin'};this.attempts=this.attempts.filter(t=>t>this.now()-60000);if(this.attempts.length>=10)return null;const pair=Buffer.from(header.slice(6),'base64').toString('utf8'),colon=pair.indexOf(':');if(this.validPassword(pair.slice(0,colon),pair.slice(colon+1))){if(this.basicCache.size>=100)this.basicCache.clear();this.basicCache.set(key,this.now()+60000);return {type:'admin'};}this.attempts.push(this.now());}
 return null;}
 logout(req){const value=(req.headers.cookie||'').split(';').map(x=>x.trim()).find(x=>x.startsWith('publisher_session='))?.slice(18);if(value)this.sessions.delete(hash(value));}
 changePassword(current,next){if(!this.validPassword(this.data.user,current))throw Error('当前密码不正确');const old=this.data.password;this.data.password=passwordRecord(next);try{this.persist();}catch(e){this.data.password=old;throw e;}this.sessions.clear();this.basicCache.clear();}
 createToken(input){if(!this.validPassword(this.data.user,input.password))throw Error('请确认当前管理员密码');if(typeof input.name!=='string'||!input.name.trim()||input.name.length>80||!Array.isArray(input.workspaces)||!input.workspaces.length||input.workspaces.some(x=>typeof x!=='string'||!x)||!Array.isArray(input.scopes)||!input.scopes.length||input.scopes.some(x=>!scopes.includes(x)))throw Error('应用名称、客户或权限无效');const days=Number(input.days);if(!Number.isInteger(days)||days<1||days>90)throw Error('有效期需要1至90天');if(this.data.tokens.length>=200)throw Error('应用令牌记录已满');const secret='vb_app_'+randomBytes(32).toString('base64url'),token={id:randomBytes(16).toString('hex'),name:input.name.trim(),workspaces:[...new Set(input.workspaces)],scopes:[...new Set(input.scopes)],expires:this.now()+days*86400000,hash:hash(secret),revoked:false};this.data.tokens.push(token);try{this.persist();}catch(e){this.data.tokens.pop();throw e;}return {token:secret,record:this.publicToken(token)};}
 publicToken(t){const {hash,...publicValue}=t;return publicValue;}
 list(){return this.data.tokens.map(t=>this.publicToken(t));}
 revoke(id){const t=this.data.tokens.find(x=>x.id===id);if(!t)throw Error('应用不存在');const old=t.revoked;t.revoked=true;try{this.persist();}catch(e){t.revoked=old;throw e;}}
 authorizeApp(principal,method,url){if(principal.type!=='app')return true;const match=url.pathname.match(/^\/api\/unified\/workspaces\/([^/]+)\/(jobs|content)$/);if(!match)return false;const workspace=decodeURIComponent(match[1]);const permission=method==='GET'&&match[2]==='jobs'?'jobs:read':method==='POST'&&match[2]==='content'?'content:import':method==='POST'&&match[2]==='jobs'?'jobs:create':null;return principal.token.workspaces.includes(workspace)&&principal.token.scopes.includes(permission);}
}
export const loginPage='<!doctype html><html lang="zh"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>登录 Publisher</title><body><h1>登录 Publisher</h1><form method="post" action="/auth/login"><label>用户名<input name="username" autocomplete="username" required></label><label>密码<input name="password" type="password" autocomplete="current-password" required maxlength="512"></label><button>登录</button></form><p>密码由管理员配置，可使用浏览器保存的密码。管理员忘记密码时，请在运行服务的 Mac 使用本地密码设置入口。</p></body></html>';
