import {interactionTarget} from './interaction-budget.js';
import { DatabaseSync } from 'node:sqlite';
import { mkdirSync } from 'node:fs';
import { dirname, isAbsolute, resolve } from 'node:path';
import { homedir } from 'node:os';
import { createHash, randomUUID } from 'node:crypto';
import { initialState } from './domain.js';
import {groupNameMatches} from './group-filters.js';
import {candidateValue,classifyEngagementPost,isNegativeReply,stablePostFingerprint} from './proactive-engagement.js';

const hash = value => createHash('sha256').update(JSON.stringify(value)).digest('hex');
const fail = message => { throw new Error(message); };
export class Store {
  constructor(path, {seedDemo = true} = {}) {
    mkdirSync(dirname(path), {recursive:true});
    this.db = new DatabaseSync(path);
    this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON; PRAGMA busy_timeout=5000;
      CREATE TABLE IF NOT EXISTS records(kind TEXT, id TEXT, workspace TEXT, value TEXT NOT NULL, PRIMARY KEY(kind,id));
      CREATE TABLE IF NOT EXISTS events(seq INTEGER PRIMARY KEY, workspace TEXT, event TEXT, value TEXT, created_at TEXT);
      CREATE TABLE IF NOT EXISTS receipts(task TEXT PRIMARY KEY, workspace TEXT, hash TEXT, outcome TEXT);
      CREATE TABLE IF NOT EXISTS attempts(id TEXT PRIMARY KEY, task TEXT, workspace TEXT, intent TEXT, phase TEXT);
      CREATE TABLE IF NOT EXISTS revisions(id TEXT PRIMARY KEY, content TEXT, workspace TEXT, body TEXT, hash TEXT);
      CREATE TABLE IF NOT EXISTS facebook_accounts(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, display_name TEXT NOT NULL, identity_type TEXT NOT NULL, external_id TEXT, profile_id TEXT NOT NULL, expected_identity TEXT NOT NULL, session_health TEXT NOT NULL, identity_verified_at TEXT, last_group_sync_at TEXT, enabled INTEGER NOT NULL DEFAULT 1);
      CREATE TABLE IF NOT EXISTS workspace_preferences(workspace TEXT NOT NULL, key TEXT NOT NULL, value TEXT NOT NULL, updated_at TEXT NOT NULL, PRIMARY KEY(workspace,key));
      CREATE TABLE IF NOT EXISTS execution_profiles(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, name TEXT NOT NULL, cdp_port INTEGER NOT NULL UNIQUE, user_data_dir TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'STOPPED', last_error TEXT);
      CREATE TABLE IF NOT EXISTS facebook_groups(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, account_id TEXT NOT NULL, name TEXT NOT NULL, url TEXT NOT NULL, external_id TEXT, membership_status TEXT NOT NULL, last_seen_at TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 1, tags TEXT, notes TEXT, UNIQUE(account_id,url));
      CREATE TABLE IF NOT EXISTS group_content(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, title TEXT, body TEXT NOT NULL, media_json TEXT NOT NULL, content_hash TEXT NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS group_jobs(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, account_id TEXT NOT NULL, group_id TEXT NOT NULL, content_id TEXT NOT NULL, expected_identity TEXT NOT NULL, profile_id TEXT NOT NULL, state TEXT NOT NULL, attempt_id TEXT, last_action TEXT, evidence_json TEXT NOT NULL, post_url TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(account_id,group_id,content_id));
      CREATE TABLE IF NOT EXISTS published_posts(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, account_id TEXT NOT NULL, group_id TEXT NOT NULL, job_id TEXT NOT NULL UNIQUE, post_url TEXT NOT NULL, observed_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS fb_comments(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, account_id TEXT NOT NULL, post_id TEXT NOT NULL, external_id TEXT, fingerprint TEXT NOT NULL, parent_id TEXT, author TEXT NOT NULL, body TEXT NOT NULL, observed_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, reply_state TEXT NOT NULL DEFAULT 'UNREPLIED', UNIQUE(post_id,fingerprint));
      CREATE TABLE IF NOT EXISTS reply_intents(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, comment_id TEXT NOT NULL, account_id TEXT NOT NULL, body TEXT NOT NULL, body_hash TEXT NOT NULL, state TEXT NOT NULL, evidence_json TEXT NOT NULL, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(comment_id,body_hash));
      CREATE TABLE IF NOT EXISTS publication_intents(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, job_id TEXT NOT NULL UNIQUE, attempt_id TEXT NOT NULL, content_hash TEXT NOT NULL, operation TEXT NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS form_snapshots(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, job_id TEXT NOT NULL, attempt_id TEXT NOT NULL, body TEXT NOT NULL, media_json TEXT NOT NULL, evidence_json TEXT NOT NULL, created_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS engagement_policies(workspace TEXT NOT NULL, account_id TEXT NOT NULL, mode TEXT NOT NULL DEFAULT 'SHADOW', topics_json TEXT NOT NULL, excluded_json TEXT NOT NULL, daily_reply_limit INTEGER NOT NULL DEFAULT 12, group_daily_limit INTEGER NOT NULL DEFAULT 3, author_weekly_limit INTEGER NOT NULL DEFAULT 2, paused INTEGER NOT NULL DEFAULT 0, cooldown_until TEXT, updated_at TEXT NOT NULL, PRIMARY KEY(workspace,account_id));
      CREATE TABLE IF NOT EXISTS engagement_candidates(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, account_id TEXT NOT NULL, comment_id TEXT NOT NULL UNIQUE, topic TEXT, risk TEXT NOT NULL, state TEXT NOT NULL, reason TEXT NOT NULL, draft TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL);
      CREATE TABLE IF NOT EXISTS quota_events(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, account_id TEXT NOT NULL, group_id TEXT, author_key TEXT, operation TEXT NOT NULL, state TEXT NOT NULL, subject_id TEXT NOT NULL, reason TEXT, reserved_at TEXT NOT NULL, consumed_at TEXT, released_at TEXT, UNIQUE(operation,subject_id,state));
      CREATE TABLE IF NOT EXISTS radar_posts(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, account_id TEXT NOT NULL, group_id TEXT NOT NULL, external_id TEXT NOT NULL, permalink TEXT NOT NULL, author TEXT NOT NULL, body TEXT NOT NULL, topic TEXT NOT NULL, observed_at TEXT NOT NULL, UNIQUE(account_id,external_id));
      CREATE TABLE IF NOT EXISTS proactive_settings(workspace TEXT NOT NULL, account_id TEXT NOT NULL, enabled INTEGER NOT NULL DEFAULT 0, scan_interval_min INTEGER NOT NULL DEFAULT 60, lookback_hours INTEGER NOT NULL DEFAULT 24, max_posts_per_group INTEGER NOT NULL DEFAULT 30, daily_limit INTEGER NOT NULL DEFAULT 5, max_followups INTEGER NOT NULL DEFAULT 5, auto_like INTEGER NOT NULL DEFAULT 0, auto_reply INTEGER NOT NULL DEFAULT 0, fact_search INTEGER NOT NULL DEFAULT 1, global_enabled INTEGER NOT NULL DEFAULT 1, account_enabled INTEGER NOT NULL DEFAULT 1, project_topics_json TEXT NOT NULL DEFAULT '[]', updated_at TEXT NOT NULL, PRIMARY KEY(workspace,account_id));
      CREATE TABLE IF NOT EXISTS engagement_posts(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, account_id TEXT NOT NULL, group_id TEXT NOT NULL, external_id TEXT, fingerprint TEXT NOT NULL, permalink TEXT, author TEXT NOT NULL, body TEXT NOT NULL, language TEXT NOT NULL, published_at TEXT, first_seen_at TEXT NOT NULL, last_seen_at TEXT NOT NULL, classification TEXT NOT NULL, relevance_score INTEGER NOT NULL, content_quality INTEGER NOT NULL, question_intent INTEGER NOT NULL, ability_to_help INTEGER NOT NULL, proposed_action TEXT NOT NULL, fact_status TEXT NOT NULL DEFAULT 'NOT_REQUIRED', reason TEXT NOT NULL, state TEXT NOT NULL, UNIQUE(account_id,group_id,fingerprint));
      CREATE TABLE IF NOT EXISTS engagement_actions(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, account_id TEXT NOT NULL, group_id TEXT NOT NULL, post_id TEXT NOT NULL, action_type TEXT NOT NULL, state TEXT NOT NULL, reply_body TEXT, attempt_id TEXT, evidence_json TEXT NOT NULL, error TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(account_id,post_id,action_type));
      CREATE TABLE IF NOT EXISTS engagement_threads(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, account_id TEXT NOT NULL, group_id TEXT NOT NULL, post_id TEXT NOT NULL, initial_comment_id TEXT, followup_count INTEGER NOT NULL DEFAULT 0, status TEXT NOT NULL, last_external_reply_at TEXT, last_our_reply_at TEXT, created_at TEXT NOT NULL, updated_at TEXT NOT NULL, UNIQUE(account_id,post_id));
      CREATE TABLE IF NOT EXISTS engagement_messages(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, thread_id TEXT NOT NULL, external_id TEXT, parent_external_id TEXT, direction TEXT NOT NULL, author TEXT, body TEXT NOT NULL, language TEXT NOT NULL, state TEXT NOT NULL, observed_at TEXT NOT NULL, UNIQUE(thread_id,external_id));
      CREATE TABLE IF NOT EXISTS engagement_daily_slots(workspace TEXT NOT NULL, account_id TEXT NOT NULL, group_id TEXT NOT NULL, post_id TEXT NOT NULL, day TEXT NOT NULL, state TEXT NOT NULL, reserved_at TEXT NOT NULL, consumed_at TEXT, PRIMARY KEY(account_id,group_id,post_id,day));
      CREATE TABLE IF NOT EXISTS engagement_fact_sources(id TEXT PRIMARY KEY, workspace TEXT NOT NULL, post_id TEXT NOT NULL, source_url TEXT NOT NULL, title TEXT, publisher TEXT, checked_at TEXT NOT NULL, supports_reply INTEGER NOT NULL, UNIQUE(post_id,source_url));
    `);
    const accountColumns=this.db.prepare('PRAGMA table_info(facebook_accounts)').all();
    if(!accountColumns.some(x=>x.name==='config_url'))this.db.exec('ALTER TABLE facebook_accounts ADD COLUMN config_url TEXT');
    if(!accountColumns.some(x=>x.name==='execution_transport'))this.db.exec('ALTER TABLE facebook_accounts ADD COLUMN execution_transport TEXT');
    const groupColumns=this.db.prepare('PRAGMA table_info(facebook_groups)').all();
    if(!groupColumns.some(x=>x.name==='proactive_engagement_enabled'))this.db.exec('ALTER TABLE facebook_groups ADD COLUMN proactive_engagement_enabled INTEGER NOT NULL DEFAULT 0');
    const proactiveColumns=this.db.prepare('PRAGMA table_info(proactive_settings)').all();
    if(!proactiveColumns.some(x=>x.name==='mode'))this.db.exec("ALTER TABLE proactive_settings ADD COLUMN mode TEXT NOT NULL DEFAULT 'LIMITED_AUTO'");
    if (seedDemo && !this.db.prepare('SELECT 1 FROM records LIMIT 1').get()) this.seed();
    this.db.prepare(`INSERT OR IGNORE INTO proactive_settings(workspace,account_id,enabled,scan_interval_min,lookback_hours,max_posts_per_group,daily_limit,max_followups,auto_like,auto_reply,fact_search,global_enabled,account_enabled,project_topics_json,updated_at,mode) SELECT workspace,id,0,60,24,30,5,5,0,0,1,1,1,'[]',?,'LIMITED_AUTO' FROM facebook_accounts`).run(new Date().toISOString());
    this.db.prepare("UPDATE engagement_candidates SET state='UNKNOWN',reason='服务重启时正在提交，必须核对，禁止重发' WHERE state='SUBMITTING'").run();
    this.db.prepare("UPDATE engagement_actions SET state='RECONCILE_PENDING',error='服务重启时动作未完成，必须核对，禁止重发',updated_at=? WHERE state='ATTEMPTING'").run(new Date().toISOString());
    this.db.prepare("UPDATE engagement_posts SET state='RECONCILE_PENDING',reason='服务重启时存在未完成动作，必须核对，禁止重发' WHERE id IN (SELECT post_id FROM engagement_actions WHERE state='RECONCILE_PENDING')").run();
    this.db.prepare("UPDATE attempts SET phase='UNKNOWN' WHERE phase='SUBMITTED'").run();
    this.db.prepare("UPDATE group_jobs SET state='UNKNOWN',last_action='服务重启时任务正在提交，必须先核对后再操作',updated_at=? WHERE state='PROCESSING'").run(new Date().toISOString());
    for (const t of this.list('tasks')) if(t.state==='SUBMITTED') { t.state='UNKNOWN'; this.put('tasks',t); }
  }
  tx(fn) { this.db.exec('BEGIN IMMEDIATE'); try { const r=fn();this.db.exec('COMMIT');return r; } catch(e){this.db.exec('ROLLBACK');throw e;} }
  put(kind,x){this.db.prepare('INSERT OR REPLACE INTO records VALUES(?,?,?,?)').run(kind,x.id,x.workspaceId??null,JSON.stringify(x));return x;}
  list(kind,workspace){return (workspace===undefined?this.db.prepare('SELECT value FROM records WHERE kind=?').all(kind):this.db.prepare('SELECT value FROM records WHERE kind=? AND workspace=?').all(kind,workspace)).map(r=>JSON.parse(r.value));}
  get(kind,id,workspace){const x=this.list(kind,workspace).find(x=>x.id===id);return x??fail('对象不属于当前客户或不存在');}
  event(workspace,event,value){this.db.prepare('INSERT INTO events(workspace,event,value,created_at) VALUES(?,?,?,?)').run(workspace,event,JSON.stringify(value),new Date().toISOString());}
  seed(){const s=initialState();this.tx(()=>{for(const kind of ['workspaces','content','tasks','groups','comments','leads']) for(const x of s[kind]) {
    if(kind==='tasks'){const c=s.content.find(c=>c.id===x.contentId);if(c?.workspaceId!==x.workspaceId)x.contentId=s.content.find(c=>c.workspaceId===x.workspaceId).id;x.state='READY';x.identityOk=true;x.executionProfileOk=true;x.revisionValid=true;x.reason='';x.approved=false;x.version=1;}
    this.put(kind,x);
  }});}
  view(workspace){const workspaces=this.list('workspaces');if(!workspace)return {mode:'agency',workspaceId:null,workspaces,content:[],tasks:[],groups:[],comments:[],leads:[],audit:[],summary:workspaces.map(w=>({id:w.id,name:w.name,tasks:this.list('tasks',w.id).length}))};
    if(!workspaces.some(w=>w.id===workspace))fail('客户不存在');
    const out={mode:'workspace',workspaceId:workspace,workspaces};for(const k of ['content','tasks','groups','comments','leads'])out[k]=this.list(k,workspace);out.audit=this.db.prepare('SELECT event,value,created_at FROM events WHERE workspace=? ORDER BY seq DESC LIMIT 50').all(workspace);return out;}
  saveWorkspace(input){const id=String(input.id||`ws-${randomUUID()}`).trim(),name=String(input.name||'').trim(),brand=String(input.brand||name).trim(),project=String(input.project||'').trim();if(!name||!brand)fail('客户名称和品牌名称不能为空');const current=input.id?this.list('workspaces').find(x=>x.id===id):null;if(input.id&&!current)fail('客户不存在');const workspace={id,name,brand,project,content_root:String(input.content_root??current?.content_root??'').trim(),library_kind:['client','enterprise'].includes(input.library_kind)?input.library_kind:(current?.library_kind||'client'),health:current?.health||'未配置',channels:Array.isArray(input.channels)?[...new Set(input.channels.map(String))]:(current?.channels||['Facebook'])};this.tx(()=>{this.put('workspaces',workspace);this.event(id,current?'workspace_updated':'workspace_created',{id,name});});return workspace;}
  facebookView(workspace){this.requireWorkspace(workspace);const accounts=this.rows('facebook_accounts',workspace),saved=this.db.prepare("SELECT value FROM workspace_preferences WHERE workspace=? AND key='selected_facebook_account'").get(workspace)?.value,selectedAccountId=accounts.some(x=>x.id===saved&&x.enabled)?saved:(accounts.find(x=>x.enabled)?.id||null);accounts.sort((a,b)=>Number(b.id===selectedAccountId)-Number(a.id===selectedAccountId));return {accounts,selectedAccountId,profiles:this.rows('execution_profiles',workspace),facebookGroups:this.rows('facebook_groups',workspace),groupContent:this.rows('group_content',workspace).map(x=>({...x,media:JSON.parse(x.media_json)})),groupJobs:this.rows('group_jobs',workspace).map(x=>({...x,evidence:JSON.parse(x.evidence_json)})),publishedPosts:this.rows('published_posts',workspace),facebookComments:this.rows('fb_comments',workspace),replyIntents:this.rows('reply_intents',workspace).map(x=>({...x,evidence:JSON.parse(x.evidence_json)})),engagementPolicies:this.rows('engagement_policies',workspace).map(x=>({...x,topics:JSON.parse(x.topics_json),excluded:JSON.parse(x.excluded_json),paused:Boolean(x.paused)})),engagementCandidates:this.rows('engagement_candidates',workspace),quotaEvents:this.rows('quota_events',workspace),radarPosts:this.rows('radar_posts',workspace),proactiveSettings:this.rows('proactive_settings',workspace).map(x=>({...x,enabled:Boolean(x.enabled),auto_like:Boolean(x.auto_like),auto_reply:Boolean(x.auto_reply),fact_search:Boolean(x.fact_search),global_enabled:Boolean(x.global_enabled),account_enabled:Boolean(x.account_enabled),project_topics:JSON.parse(x.project_topics_json)})),proactivePosts:this.rows('engagement_posts',workspace),proactiveActions:this.rows('engagement_actions',workspace).map(x=>({...x,evidence:JSON.parse(x.evidence_json)})),proactiveThreads:this.rows('engagement_threads',workspace),proactiveMessages:this.rows('engagement_messages',workspace),proactiveDailySlots:this.rows('engagement_daily_slots',workspace),proactiveFactSources:this.rows('engagement_fact_sources',workspace)};}
  rows(table,workspace){return this.db.prepare(`SELECT * FROM ${table} WHERE workspace=? ORDER BY rowid DESC`).all(workspace).map(x=>({...x,enabled:x.enabled===undefined?undefined:Boolean(x.enabled)}));}
  requireWorkspace(workspace){if(!this.list('workspaces').some(x=>x.id===workspace))fail('客户不存在');}
  saveAccount(workspace,input){this.requireWorkspace(workspace);const id=input.id||randomUUID(),name=String(input.display_name||'').trim(),profileId=String(input.profile_id||'').trim(),expected=String(input.expected_identity||name).trim(),configUrl=localConfigUrl(input.config_url);if(!name||!profileId||!expected)fail('账号名称、执行环境和预期身份不能为空');const current=input.id?this.db.prepare('SELECT * FROM facebook_accounts WHERE id=? AND workspace=?').get(id,workspace):null;if(input.id&&!current)fail('账号不属于当前客户或不存在');const transport=input.execution_transport==null?(current?.execution_transport||null):String(input.execution_transport);if(transport!==null&&!['API','BROWSER'].includes(transport))fail('执行方式必须为 API 或 BROWSER');const externalId=input.external_id===undefined?(current?.external_id||null):(String(input.external_id).trim()||null);if(externalId&&!/^\d+$/.test(externalId))fail('Facebook Page ID 必须是数字');this.tx(()=>{if(!this.db.prepare('SELECT 1 FROM execution_profiles WHERE id=? AND workspace=?').get(profileId,workspace))fail('执行环境不属于当前客户');this.db.prepare(`INSERT INTO facebook_accounts(id,workspace,display_name,identity_type,external_id,profile_id,expected_identity,session_health,identity_verified_at,last_group_sync_at,enabled,config_url,execution_transport) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET display_name=excluded.display_name,identity_type=excluded.identity_type,external_id=excluded.external_id,profile_id=excluded.profile_id,expected_identity=excluded.expected_identity,enabled=excluded.enabled,config_url=excluded.config_url,execution_transport=excluded.execution_transport`).run(id,workspace,name,input.identity_type||'PROFILE',externalId,profileId,expected,current?.session_health||'UNKNOWN',current?.identity_verified_at||null,current?.last_group_sync_at||null,input.enabled===false?0:1,configUrl||current?.config_url||null,transport);this.event(workspace,current?'account_updated':'account_created',{id});});this.ensureProactiveAccount(workspace,id);if(!this.facebookView(workspace).selectedAccountId)this.selectAccount(workspace,id);return this.db.prepare('SELECT * FROM facebook_accounts WHERE id=?').get(id);}
  selectAccount(workspace,id){const account=this.account(workspace,id);this.db.prepare("INSERT INTO workspace_preferences(workspace,key,value,updated_at) VALUES(?,'selected_facebook_account',?,?) ON CONFLICT(workspace,key) DO UPDATE SET value=excluded.value,updated_at=excluded.updated_at").run(workspace,id,new Date().toISOString());return account;}
  saveProfile(workspace,input){this.requireWorkspace(workspace);const id=input.id||randomUUID(),name=String(input.name||'').trim(),port=Number(input.cdp_port);if(!name||!Number.isInteger(port)||port<1024||port>65535)fail('执行环境名称或调试端口无效');const dir=String(input.user_data_dir||'').trim(),resolved=resolve(dir);if(!isAbsolute(dir)||['/',homedir()].includes(resolved)||/\/CloudStorage\/GoogleDrive\//.test(resolved))fail('Chrome 数据目录必须是本机专用绝对路径，不能填写网页或 Google Drive 链接');const current=input.id?this.db.prepare('SELECT * FROM execution_profiles WHERE id=? AND workspace=?').get(id,workspace):null;if(input.id&&!current)fail('执行环境不属于当前客户');const conflict=this.db.prepare('SELECT id FROM execution_profiles WHERE id<>? AND (cdp_port=? OR user_data_dir=?)').get(id,port,dir);if(conflict)fail('端口或浏览器数据目录已被其他执行环境使用');this.db.prepare(`INSERT INTO execution_profiles(id,workspace,name,cdp_port,user_data_dir,status,last_error) VALUES(?,?,?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET name=excluded.name,cdp_port=excluded.cdp_port,user_data_dir=excluded.user_data_dir,status='STOPPED',last_error=NULL`).run(id,workspace,name,port,dir,current?.status||'STOPPED',current?.last_error||null);return this.db.prepare('SELECT * FROM execution_profiles WHERE id=?').get(id);}
  addGroup(workspace,input){this.requireWorkspace(workspace);const account=this.account(workspace,input.account_id),url=normalizeGroupUrl(input.url),id=input.id||randomUUID(),time=new Date().toISOString();this.db.prepare(`INSERT INTO facebook_groups(id,workspace,account_id,name,url,external_id,membership_status,last_seen_at,enabled,tags,notes,proactive_engagement_enabled) VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,url) DO UPDATE SET name=excluded.name,membership_status='JOINED',last_seen_at=excluded.last_seen_at`).run(id,workspace,account.id,String(input.name||url).trim(),url,groupId(url),'JOINED',time,input.enabled===false?0:1,input.tags||null,input.notes||null,input.proactive_engagement_enabled?1:0);return this.db.prepare('SELECT * FROM facebook_groups WHERE account_id=? AND url=?').get(account.id,url);}
  syncGroups(workspace,accountId,groups){const account=this.account(workspace,accountId),time=new Date().toISOString();return this.tx(()=>{this.db.prepare("UPDATE facebook_groups SET membership_status='STALE' WHERE workspace=? AND account_id=?").run(workspace,accountId);for(const g of groups)this.addGroup(workspace,{...g,account_id:accountId});this.db.prepare("UPDATE facebook_accounts SET last_group_sync_at=?,session_health='HEALTHY',identity_verified_at=? WHERE id=?").run(time,time,account.id);return this.rows('facebook_groups',workspace).filter(x=>x.account_id===accountId);});}
  createContent(workspace,input){this.requireWorkspace(workspace);const body=String(input.body||'').trim(),media=(input.media||[]).map(String);if(!body&&!media.length)fail('正文或媒体至少需要一项');const id=randomUUID(),contentHash=hash({body,media});this.db.prepare('INSERT INTO group_content VALUES(?,?,?,?,?,?,?)').run(id,workspace,String(input.title||'').trim(),body,JSON.stringify(media),contentHash,new Date().toISOString());return this.db.prepare('SELECT * FROM group_content WHERE id=?').get(id);}
  createGroupJobs(workspace,input){
    const account=this.account(workspace,input.account_id),contentIds=[...new Set(input.content_ids||[input.content_id])];
    if(!contentIds.length||contentIds.length>20)fail('请选择 1–20 个内容版本');
    const contents=contentIds.map(id=>this.db.prepare('SELECT * FROM group_content WHERE id=? AND workspace=?').get(id,workspace)||fail('内容不属于当前客户'));
    const ids=[...new Set(input.group_ids||[])];if(!ids.length)fail('至少选择一个群组');
    return this.tx(()=>contents.flatMap(content=>ids.map(groupId=>{
      const group=this.db.prepare("SELECT * FROM facebook_groups WHERE id=? AND workspace=? AND account_id=? AND enabled=1 AND membership_status='JOINED'").get(groupId,workspace,account.id);if(!group)fail('群组不属于所选账号、未在本次同步中确认或已停用');
      if(!groupNameMatches(group.name,{include:input.group_name_include,exclude:input.group_name_exclude}))fail(`群组“${group.name}”不符合当前名称筛选，未创建任务`);
      const id=randomUUID(),time=new Date().toISOString();
      const result=this.db.prepare(`INSERT OR IGNORE INTO group_jobs VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)`).run(id,workspace,account.id,group.id,content.id,account.expected_identity,account.profile_id,'PENDING',null,'任务已创建',JSON.stringify({content_hash:content.content_hash}),null,time,time);
      const job=this.db.prepare('SELECT * FROM group_jobs WHERE account_id=? AND group_id=? AND content_id=?').get(account.id,group.id,content.id);
      return {...job,was_created:Boolean(result.changes)};
    })));
  }
  beginPrepare(workspace,jobId,actualIdentity){return this.tx(()=>{const job=this.job(workspace,jobId),account=this.account(workspace,job.account_id);if(!['PENDING','FAILED','BLOCKED'].includes(job.state))fail('当前任务不能重新准备');if(account.expected_identity!==actualIdentity)fail('实际 Facebook 身份与账号配置不一致，已在写入前阻止');const attempt=randomUUID(),time=new Date().toISOString();this.db.prepare("UPDATE group_jobs SET state='PREPARING',attempt_id=?,last_action='正在准备真实群组编辑器',updated_at=? WHERE id=?").run(attempt,time,jobId);return this.job(workspace,jobId);});}
  finishPrepare(workspace,jobId,evidence){const job=this.job(workspace,jobId);if(job.state!=='PREPARING')fail('任务不在准备状态');this.db.prepare("UPDATE group_jobs SET state='WAITING_FOR_USER',last_action='内容已核对，等待人工最终点击',evidence_json=?,updated_at=? WHERE id=?").run(JSON.stringify(evidence),new Date().toISOString(),jobId);return this.job(workspace,jobId);}
  beginSubmit(workspace,jobId,snapshot){return this.tx(()=>{const job=this.job(workspace,jobId);if(job.state!=='WAITING_FOR_USER')fail('任务尚未完成表单核对');const content=this.db.prepare('SELECT * FROM group_content WHERE id=? AND workspace=?').get(job.content_id,workspace)||fail('内容不存在');const time=new Date().toISOString(),intent=randomUUID();this.db.prepare('INSERT INTO publication_intents VALUES(?,?,?,?,?,?,?)').run(intent,workspace,job.id,job.attempt_id,content.content_hash,'FACEBOOK_GROUP_POST',time);this.db.prepare('INSERT INTO form_snapshots VALUES(?,?,?,?,?,?,?,?)').run(randomUUID(),workspace,job.id,job.attempt_id,content.body,content.media_json,JSON.stringify(snapshot||{}),time);this.db.prepare("UPDATE group_jobs SET state='PROCESSING',last_action='已记录发布意图，正在提交一次',updated_at=? WHERE id=?").run(time,job.id);return this.job(workspace,job.id);});}
  failBeforeSubmit(workspace,jobId,reason){const job=this.job(workspace,jobId);if(!['PREPARING','WAITING_FOR_USER'].includes(job.state))fail('任务已经进入提交阶段，不能标记为提交前失败');this.db.prepare("UPDATE group_jobs SET state='FAILED',last_action=?,updated_at=? WHERE id=?").run(reason||'提交前检查失败',new Date().toISOString(),jobId);return this.job(workspace,jobId);}
  blockUnstarted(workspace,jobId,reason){const job=this.job(workspace,jobId);if(job.state!=='PENDING')fail('只能阻止尚未开始的任务');this.db.prepare("UPDATE group_jobs SET state='BLOCKED',last_action=?,updated_at=? WHERE id=?").run(reason||'同批前序任务失败，尚未开始发布',new Date().toISOString(),jobId);return this.job(workspace,jobId);}
  markUnknown(workspace,jobId,reason){const job=this.job(workspace,jobId);if(!['PREPARING','WAITING_FOR_USER','PROCESSING'].includes(job.state))fail('当前任务不能标记未知');this.db.prepare("UPDATE group_jobs SET state='UNKNOWN',last_action=?,updated_at=? WHERE id=?").run(reason||'提交结果不确定，必须先核对',new Date().toISOString(),jobId);return this.job(workspace,jobId);}
  claimPost(workspace,jobId,url,readback){return this.tx(()=>{const job=this.job(workspace,jobId),postUrl=normalizeFacebookUrl(url);if(job.state==='PUBLISHED'){if(job.post_url!==postUrl)fail('该任务已登记不同的帖子链接');if(readback?.method){const evidence={...JSON.parse(job.evidence_json||'{}'),readback};this.db.prepare("UPDATE group_jobs SET evidence_json=?,last_action='已回读 Facebook 帖子并登记',updated_at=? WHERE id=?").run(JSON.stringify(evidence),new Date().toISOString(),job.id);return this.job(workspace,job.id);}return job;}if(!['WAITING_FOR_USER','PROCESSING','UNKNOWN','FAILED'].includes(job.state))fail('当前任务不能登记发布结果');if(!['MANUAL_POST_BROWSER_READBACK','AUTO_POST_BROWSER_READBACK'].includes(readback?.method))fail('必须先独立回读 Facebook 帖子');const duplicate=this.db.prepare('SELECT job_id FROM published_posts WHERE workspace=? AND post_url=? AND job_id<>?').get(workspace,postUrl,job.id);if(duplicate)fail('此帖子已登记到另一任务，不能重复认领');const id=randomUUID(),time=new Date().toISOString(),evidence={...JSON.parse(job.evidence_json||'{}'),readback};this.db.prepare('INSERT INTO published_posts VALUES(?,?,?,?,?,?,?)').run(id,workspace,job.account_id,job.group_id,job.id,postUrl,time);this.db.prepare("UPDATE group_jobs SET state='PUBLISHED',post_url=?,last_action='已回读 Facebook 帖子并登记',evidence_json=?,updated_at=? WHERE id=?").run(postUrl,JSON.stringify(evidence),time,job.id);return this.job(workspace,job.id);});}
  upsertComments(workspace,postId,items){const post=this.db.prepare('SELECT * FROM published_posts WHERE id=? AND workspace=?').get(postId,workspace);if(!post)fail('发布记录不属于当前客户');const time=new Date().toISOString();return this.tx(()=>items.map(item=>{const body=String(item.body||'').trim(),author=String(item.author||'').trim();if(!body||!author)fail('评论作者和正文不能为空');const fp=item.external_id||hash([post.post_url,item.parent_id||'',author,body]),id=randomUUID();this.db.prepare(`INSERT INTO fb_comments VALUES(?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(post_id,fingerprint) DO UPDATE SET last_seen_at=excluded.last_seen_at,body=excluded.body,author=excluded.author`).run(id,workspace,post.account_id,post.id,item.external_id||null,fp,item.parent_id||null,author,body,item.observed_at||time,time,'UNREPLIED');return this.db.prepare('SELECT * FROM fb_comments WHERE post_id=? AND fingerprint=?').get(post.id,fp);}));}
  upsertPagePost(workspace,accountId,item){this.account(workspace,accountId);const externalId=String(item.id||'').trim();if(!externalId)fail('Facebook 帖子缺少 ID');const url=String(item.permalink_url||`https://www.facebook.com/${externalId}`).trim(),jobId=`page:${externalId}`,time=new Date().toISOString(),existing=this.db.prepare('SELECT * FROM published_posts WHERE workspace=? AND job_id=?').get(workspace,jobId);if(existing){this.db.prepare('UPDATE published_posts SET post_url=?,observed_at=? WHERE id=?').run(url,time,existing.id);return this.db.prepare('SELECT * FROM published_posts WHERE id=?').get(existing.id)}const id=randomUUID();this.db.prepare('INSERT INTO published_posts VALUES(?,?,?,?,?,?,?)').run(id,workspace,accountId,'PAGE',jobId,url,time);return this.db.prepare('SELECT * FROM published_posts WHERE id=?').get(id);}
  createReplyIntent(workspace,commentId,body){const comment=this.db.prepare('SELECT * FROM fb_comments WHERE id=? AND workspace=?').get(commentId,workspace);if(!comment)fail('评论不属于当前客户');const text=String(body||'').trim();if(!text)fail('回复不能为空');const digest=hash(text),existing=this.db.prepare('SELECT * FROM reply_intents WHERE comment_id=? AND body_hash=?').get(commentId,digest);if(existing)fail('相同回复已存在，禁止重复发送');const id=randomUUID(),time=new Date().toISOString();this.db.prepare('INSERT INTO reply_intents VALUES(?,?,?,?,?,?,?,?,?,?)').run(id,workspace,commentId,comment.account_id,text,digest,'PENDING',JSON.stringify({}),time,time);return this.db.prepare('SELECT * FROM reply_intents WHERE id=?').get(id);}
  replyIntent(workspace,id){return this.db.prepare('SELECT * FROM reply_intents WHERE id=? AND workspace=?').get(id,workspace)||fail('回复意图不存在');}
  comment(workspace,id){return this.db.prepare('SELECT * FROM fb_comments WHERE id=? AND workspace=?').get(id,workspace)||fail('评论不存在');}
  markReplyPreflight(workspace,id,evidence){const intent=this.replyIntent(workspace,id),allowed=evidence?.would_send===true;this.db.prepare('UPDATE reply_intents SET state=?,evidence_json=?,updated_at=? WHERE id=?').run(allowed?'READY_FOR_APPROVAL':'BLOCKED',JSON.stringify(evidence||{}),new Date().toISOString(),id);return this.replyIntent(workspace,intent.id);}
  saveEngagementPolicy(workspace,input){const account=this.account(workspace,input.account_id),mode=['SHADOW','AUTO_LOW_RISK'].includes(input.mode)?input.mode:'SHADOW',topics=splitTerms(input.topics),excluded=splitTerms(input.excluded),daily=bounded(input.daily_reply_limit,1,12,12),group=bounded(input.group_daily_limit,1,3,3),author=bounded(input.author_weekly_limit,1,2,2),time=new Date().toISOString();this.db.prepare(`INSERT INTO engagement_policies VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace,account_id) DO UPDATE SET mode=excluded.mode,topics_json=excluded.topics_json,excluded_json=excluded.excluded_json,daily_reply_limit=excluded.daily_reply_limit,group_daily_limit=excluded.group_daily_limit,author_weekly_limit=excluded.author_weekly_limit,paused=excluded.paused,cooldown_until=excluded.cooldown_until,updated_at=excluded.updated_at`).run(workspace,account.id,mode,JSON.stringify(topics),JSON.stringify(excluded),daily,group,author,input.paused?1:0,input.cooldown_until||null,time);return this.engagementPolicy(workspace,account.id);}
  engagementPolicy(workspace,accountId){const row=this.db.prepare('SELECT * FROM engagement_policies WHERE workspace=? AND account_id=?').get(workspace,accountId);return row?{...row,topics:JSON.parse(row.topics_json),excluded:JSON.parse(row.excluded_json),paused:Boolean(row.paused)}:null;}
  buildEngagementCandidates(workspace,accountId){const policy=this.engagementPolicy(workspace,accountId)||fail('请先保存主题与额度规则'),comments=this.db.prepare('SELECT * FROM fb_comments WHERE workspace=? AND account_id=? ORDER BY observed_at DESC').all(workspace,accountId),now=new Date().toISOString();return this.tx(()=>comments.map(comment=>{const classified=classifyComment(comment.body,policy),existing=this.db.prepare('SELECT * FROM engagement_candidates WHERE comment_id=?').get(comment.id),id=existing?.id||randomUUID(),locked=existing&&['QUOTA_RESERVED','SUBMITTING','UNKNOWN','REPLIED'].includes(existing.state),state=locked?existing.state:classified.state,draft=locked?existing.draft:draftReply(comment.body,classified);this.db.prepare(`INSERT INTO engagement_candidates VALUES(?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(comment_id) DO UPDATE SET topic=excluded.topic,risk=excluded.risk,state=excluded.state,draft=excluded.draft,reason=CASE WHEN engagement_candidates.state IN ('QUOTA_RESERVED','SUBMITTING','UNKNOWN','REPLIED') THEN engagement_candidates.reason ELSE excluded.reason END,updated_at=excluded.updated_at`).run(id,workspace,accountId,comment.id,classified.topic,classified.risk,state,classified.reason,draft,existing?.created_at||now,now);return this.db.prepare('SELECT * FROM engagement_candidates WHERE id=?').get(id)}));}
  ingestRadarPosts(workspace,accountId,items){const account=this.account(workspace,accountId),time=new Date().toISOString();return items.map(item=>{const group=this.db.prepare('SELECT * FROM facebook_groups WHERE id=? AND workspace=? AND account_id=? AND enabled=1').get(item.group_id,workspace,account.id)||fail('雷达结果来自未授权群组'),external=String(item.external_id||'').trim(),body=String(item.body||'').trim(),author=String(item.author||'Facebook 用户').trim();if(!external||!body)fail('雷达结果缺少帖子 ID 或正文');const existing=this.db.prepare('SELECT * FROM radar_posts WHERE account_id=? AND external_id=?').get(account.id,external),id=existing?.id||randomUUID();this.db.prepare(`INSERT INTO radar_posts VALUES(?,?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,external_id) DO UPDATE SET permalink=excluded.permalink,author=excluded.author,body=excluded.body,topic=excluded.topic,observed_at=excluded.observed_at`).run(id,workspace,account.id,group.id,external,item.permalink,author,body,item.topic,time);let parent=this.db.prepare('SELECT * FROM published_posts WHERE workspace=? AND job_id=?').get(workspace,`radar-group:${group.id}`);if(!parent){const parentId=randomUUID();this.db.prepare('INSERT INTO published_posts VALUES(?,?,?,?,?,?,?)').run(parentId,workspace,account.id,group.id,`radar-group:${group.id}`,group.url,time);parent=this.db.prepare('SELECT * FROM published_posts WHERE id=?').get(parentId)}this.upsertComments(workspace,parent.id,[{external_id:external,author,body,observed_at:time}]);return this.db.prepare('SELECT * FROM radar_posts WHERE id=?').get(id)});}
  quotaStatus(workspace,accountId){const policy=this.engagementPolicy(workspace,accountId),sinceDay=new Date(Date.now()-86400000).toISOString(),sinceWeek=new Date(Date.now()-7*86400000).toISOString(),used=this.db.prepare("SELECT count(*) n FROM quota_events WHERE workspace=? AND account_id=? AND operation='REPLY' AND state IN ('RESERVED','CONSUMED') AND reserved_at>=?").get(workspace,accountId,sinceDay).n;const shared=this.interactionBudget?.status(workspace,accountId);return {policy,used:shared?.used??used,dailyLimit:shared?.dailyLimit??(policy?.daily_reply_limit||12),remaining:shared?.remaining??Math.max(0,(policy?.daily_reply_limit||12)-used),state:policy?.paused?'PAUSED':policy?.cooldown_until&&policy.cooldown_until>new Date().toISOString()?'COOLDOWN':used>=(policy?.daily_reply_limit||12)?'THROTTLED':'NORMAL',weekSince:sinceWeek};}
  reserveReplyQuota(workspace,candidateId){return this.tx(()=>this.reserveReplyQuotaInside(workspace,candidateId));}
  reserveReplyQuotaInside(workspace,candidateId){const candidate=this.db.prepare('SELECT * FROM engagement_candidates WHERE id=? AND workspace=?').get(candidateId,workspace)||fail('候选回复不存在'),comment=this.comment(workspace,candidate.comment_id),post=this.db.prepare('SELECT * FROM published_posts WHERE id=?').get(comment.post_id),status=this.quotaStatus(workspace,candidate.account_id),policy=status.policy||fail('额度规则不存在');if(candidate.state!=='REPLY_CANDIDATE'||candidate.risk!=='LOW')fail('只有低风险回复候选可以自动执行');if(policy.mode!=='AUTO_LOW_RISK')fail('当前为影子模式，不会发送');if(status.state!=='NORMAL')fail(`额度控制器已阻止：${status.state}`);const day=new Date(Date.now()-86400000).toISOString(),week=new Date(Date.now()-7*86400000).toISOString(),groupUsed=this.db.prepare("SELECT count(*) n FROM quota_events WHERE workspace=? AND account_id=? AND group_id=? AND operation='REPLY' AND state IN ('RESERVED','CONSUMED') AND reserved_at>=?").get(workspace,candidate.account_id,post.group_id,day).n,authorUsed=this.db.prepare("SELECT count(*) n FROM quota_events WHERE workspace=? AND account_id=? AND author_key=? AND operation='REPLY' AND state IN ('RESERVED','CONSUMED') AND reserved_at>=?").get(workspace,candidate.account_id,comment.author,week).n;if(groupUsed>=policy.group_daily_limit)fail('该群组今日回复额度已用完');if(authorUsed>=policy.author_weekly_limit)fail('该作者本周互动额度已用完');this.interactionBudget?.reserve({workspace,accountId:candidate.account_id,groupId:post.group_id,author:comment.author,target:interactionTarget(post.post_url,post.id),owner:'theme:'+candidate.id});const id=randomUUID(),time=new Date().toISOString();this.db.prepare('INSERT INTO quota_events VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(id,workspace,candidate.account_id,post.group_id,comment.author,'REPLY','RESERVED',candidate.id,'低风险自动回复预留',time,null,null);this.db.prepare("UPDATE engagement_candidates SET state='QUOTA_RESERVED',updated_at=? WHERE id=?").run(time,candidate.id);return {reservation:this.db.prepare('SELECT * FROM quota_events WHERE id=?').get(id),status:this.quotaStatus(workspace,candidate.account_id)};}
  releaseQuota(workspace,id,reason='提交前释放'){const row=this.db.prepare("SELECT * FROM quota_events WHERE id=? AND workspace=? AND state='RESERVED'").get(id,workspace)||fail('额度预留不存在或不可释放'),time=new Date().toISOString();if(this.engagementCandidate(workspace,row.subject_id).state!=='QUOTA_RESERVED')fail('可能已提交，禁止释放额度；请先核对结果');this.interactionBudget?.finish('theme:'+row.subject_id,'RELEASED');this.db.prepare("UPDATE quota_events SET state='RELEASED',reason=?,released_at=? WHERE id=?").run(reason,time,id);this.db.prepare("UPDATE engagement_candidates SET state='REPLY_CANDIDATE',updated_at=? WHERE id=?").run(time,row.subject_id);return this.quotaStatus(workspace,row.account_id);}
  engagementCandidate(workspace,id){return this.db.prepare('SELECT * FROM engagement_candidates WHERE id=? AND workspace=?').get(id,workspace)||fail('互动候选不存在');}
  beginAutoReply(workspace,candidateId,reservationId){const candidate=this.engagementCandidate(workspace,candidateId),reservation=this.db.prepare("SELECT * FROM quota_events WHERE id=? AND workspace=? AND subject_id=? AND state='RESERVED'").get(reservationId,workspace,candidateId)||fail('额度预留无效');const policy=this.engagementPolicy(workspace,candidate.account_id);if(candidate.state!=='QUOTA_RESERVED'||!policy||policy.paused||policy.mode!=='AUTO_LOW_RISK'||(policy.cooldown_until&&policy.cooldown_until>new Date().toISOString()))fail('规则已变化或账号暂停，已阻止提交');this.db.prepare("UPDATE engagement_candidates SET state='SUBMITTING',updated_at=? WHERE id=?").run(new Date().toISOString(),candidate.id);return {candidate,reservation};}
  finishAutoReply(workspace,candidateId,reservationId,evidence){const candidate=this.engagementCandidate(workspace,candidateId),comment=this.comment(workspace,candidate.comment_id),time=new Date().toISOString();return this.tx(()=>{this.db.prepare("UPDATE quota_events SET state='CONSUMED',reason='发送并回读成功',consumed_at=? WHERE id=? AND workspace=? AND state='RESERVED'").run(time,reservationId,workspace);this.interactionBudget?.finish('theme:'+candidate.id,'CONSUMED');this.db.prepare("UPDATE engagement_candidates SET state='REPLIED',reason='已发送并通过独立回读确认',updated_at=? WHERE id=?").run(time,candidate.id);this.db.prepare("UPDATE fb_comments SET reply_state='REPLIED' WHERE id=?").run(comment.id);this.event(workspace,'auto_reply_readback',{candidate_id:candidate.id,reservation_id:reservationId,reply_id:evidence.reply_id});return this.engagementCandidate(workspace,candidate.id)});}
  markAutoReplyUnknown(workspace,candidateId,reservationId,reason){const candidate=this.engagementCandidate(workspace,candidateId),time=new Date().toISOString();this.db.prepare("UPDATE engagement_candidates SET state='UNKNOWN',reason=?,updated_at=? WHERE id=?").run(reason||'提交结果不明确，必须核对，禁止重发',time,candidate.id);this.db.prepare("UPDATE quota_events SET reason=? WHERE id=? AND workspace=? AND state='RESERVED'").run('结果待核对，额度保持锁定',reservationId,workspace);this.event(workspace,'auto_reply_unknown',{candidate_id:candidate.id,reservation_id:reservationId});return this.engagementCandidate(workspace,candidate.id);}
  ensureProactiveAccount(workspace,accountId){const account=this.db.prepare('SELECT id FROM facebook_accounts WHERE id=? AND workspace=?').get(accountId,workspace)||fail('Facebook 账号不属于当前客户');this.db.prepare(`INSERT OR IGNORE INTO proactive_settings(workspace,account_id,enabled,scan_interval_min,lookback_hours,max_posts_per_group,daily_limit,max_followups,auto_like,auto_reply,fact_search,global_enabled,account_enabled,project_topics_json,updated_at,mode) VALUES(?,?,0,60,24,30,5,5,0,0,1,1,1,'[]',?,'LIMITED_AUTO')`).run(workspace,account.id,new Date().toISOString());return this.proactiveSettings(workspace,account.id);}
  saveProactiveSettings(workspace,input){const account=this.account(workspace,input.account_id),time=new Date().toISOString(),current=this.proactiveSettings(workspace,account.id)||this.ensureProactiveAccount(workspace,account.id),value=(name,fallback,min,max)=>bounded(input[name]??current?.[name],min,max,fallback),enabled=name=>input[name]===undefined?Number(current?.[name]??0):input[name]?1:0,topics=splitTerms(input.project_topics??current?.project_topics??[]),mode=['SHADOW','LIMITED_AUTO'].includes(input.mode)?input.mode:(current?.mode||'LIMITED_AUTO');this.db.prepare(`INSERT INTO proactive_settings(workspace,account_id,enabled,scan_interval_min,lookback_hours,max_posts_per_group,daily_limit,max_followups,auto_like,auto_reply,fact_search,global_enabled,account_enabled,project_topics_json,updated_at,mode) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(workspace,account_id) DO UPDATE SET enabled=excluded.enabled,scan_interval_min=excluded.scan_interval_min,lookback_hours=excluded.lookback_hours,max_posts_per_group=excluded.max_posts_per_group,daily_limit=excluded.daily_limit,max_followups=excluded.max_followups,auto_like=excluded.auto_like,auto_reply=excluded.auto_reply,fact_search=excluded.fact_search,global_enabled=excluded.global_enabled,account_enabled=excluded.account_enabled,project_topics_json=excluded.project_topics_json,updated_at=excluded.updated_at,mode=excluded.mode`).run(workspace,account.id,enabled('enabled'),value('scan_interval_min',60,15,1440),value('lookback_hours',24,1,168),value('max_posts_per_group',30,1,100),value('daily_limit',5,1,5),value('max_followups',5,0,5),enabled('auto_like'),enabled('auto_reply'),input.fact_search===undefined?Number(current?.fact_search??1):input.fact_search?1:0,input.global_enabled===undefined?Number(current?.global_enabled??1):input.global_enabled?1:0,input.account_enabled===undefined?Number(current?.account_enabled??1):input.account_enabled?1:0,JSON.stringify(topics),time,mode);return this.proactiveSettings(workspace,account.id);}
  proactiveSettings(workspace,accountId){const row=this.db.prepare('SELECT * FROM proactive_settings WHERE workspace=? AND account_id=?').get(workspace,accountId);return row?{...row,enabled:Boolean(row.enabled),auto_like:Boolean(row.auto_like),auto_reply:Boolean(row.auto_reply),fact_search:Boolean(row.fact_search),global_enabled:Boolean(row.global_enabled),account_enabled:Boolean(row.account_enabled),project_topics:JSON.parse(row.project_topics_json)}:null;}
  setGroupProactive(workspace,groupId,enabled){const result=this.db.prepare('UPDATE facebook_groups SET proactive_engagement_enabled=? WHERE id=? AND workspace=?').run(enabled?1:0,groupId,workspace);if(!result.changes)fail('群组不属于当前客户');return this.db.prepare('SELECT * FROM facebook_groups WHERE id=?').get(groupId);}
  ingestEngagementPosts(workspace,accountId,items){const account=this.account(workspace,accountId),settings=this.proactiveSettings(workspace,account.id)||fail('请先保存主动互动设置'),now=new Date().toISOString();return this.tx(()=>items.map(item=>{const group=this.db.prepare("SELECT * FROM facebook_groups WHERE id=? AND workspace=? AND account_id=? AND membership_status='JOINED' AND enabled=1 AND proactive_engagement_enabled=1").get(item.group_id,workspace,account.id)||fail('帖子来自未授权、未加入或未开启主动互动的群组'),fingerprint=String(item.external_id||'').trim()||stablePostFingerprint(item),classification=classifyEngagementPost(item,{project_topics:settings.project_topics,group_topics:splitTerms(group.tags),group_relevant:true}),existing=this.db.prepare('SELECT * FROM engagement_posts WHERE account_id=? AND group_id=? AND fingerprint=?').get(account.id,group.id,fingerprint),id=existing?.id||randomUUID(),factStatus=classification.needs_fact_search?'REQUIRED':'NOT_REQUIRED',state=classification.action==='SKIP'?'SKIPPED':classification.needs_fact_search?'FACT_REQUIRED':'CANDIDATE';this.db.prepare(`INSERT INTO engagement_posts VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,group_id,fingerprint) DO UPDATE SET permalink=excluded.permalink,author=excluded.author,body=excluded.body,language=excluded.language,published_at=excluded.published_at,last_seen_at=excluded.last_seen_at,classification=excluded.classification,relevance_score=excluded.relevance_score,content_quality=excluded.content_quality,question_intent=excluded.question_intent,ability_to_help=excluded.ability_to_help,proposed_action=excluded.proposed_action,fact_status=CASE WHEN engagement_posts.fact_status='VERIFIED' THEN engagement_posts.fact_status ELSE excluded.fact_status END,reason=excluded.reason,state=CASE WHEN engagement_posts.state IN ('ATTEMPTING','LIKED','REPLIED','LIKED_AND_REPLIED','UNKNOWN','RECONCILE_PENDING','PARTIAL_RETRY') THEN engagement_posts.state WHEN engagement_posts.fact_status='VERIFIED' AND excluded.state='FACT_REQUIRED' THEN 'FACT_VERIFIED' ELSE excluded.state END`).run(id,workspace,account.id,group.id,item.external_id||null,fingerprint,item.permalink||null,String(item.author||'Facebook 用户').trim(),String(item.body||'').trim(),classification.language,item.published_at||null,existing?.first_seen_at||now,now,classification.classification,classification.relevance_score,classification.content_quality,classification.question_intent,classification.ability_to_help,classification.action,factStatus,classification.reason,state);return this.db.prepare('SELECT * FROM engagement_posts WHERE id=?').get(id)}));}
  rankedEngagementCandidates(workspace,accountId){const settings=this.proactiveSettings(workspace,accountId)||fail('请先保存主动互动设置'),rows=this.db.prepare("SELECT * FROM engagement_posts WHERE workspace=? AND account_id=? AND state IN ('CANDIDATE','FACT_VERIFIED','PARTIAL_RETRY')").all(workspace,accountId).map(x=>({...x,value_score:candidateValue(x)})).sort((a,b)=>b.value_score-a.value_score),byGroup=new Map(),result=[];for(const row of rows){const used=byGroup.get(row.group_id)||0;if(used>=settings.daily_limit)continue;byGroup.set(row.group_id,used+1);result.push(row)}return result;}
  addFactSource(workspace,postId,input){const post=this.proactivePost(workspace,postId),url=String(input.source_url||'').trim();if(!/^https:\/\//.test(url))fail('事实来源必须是 HTTPS 地址');const id=randomUUID(),time=new Date().toISOString();this.db.prepare('INSERT OR REPLACE INTO engagement_fact_sources VALUES(?,?,?,?,?,?,?,?)').run(id,workspace,post.id,url,String(input.title||''),String(input.publisher||''),time,input.supports_reply?1:0);const supported=this.db.prepare('SELECT count(*) n FROM engagement_fact_sources WHERE post_id=? AND supports_reply=1').get(post.id).n>0;this.db.prepare("UPDATE engagement_posts SET fact_status=?,state=?,reason=? WHERE id=?").run(supported?'VERIFIED':'UNVERIFIED',supported?'FACT_VERIFIED':'FACT_REQUIRED',supported?'事实来源已记录，可重新生成回复':'尚无可靠来源，禁止回复',post.id);return this.proactivePost(workspace,post.id);}
  reserveProactivePost(workspace,postId,replyBody){return this.tx(()=>{
    const post=this.proactivePost(workspace,postId),settings=this.proactiveSettings(workspace,post.account_id)||fail('主动互动设置不存在'),account=this.account(workspace,post.account_id),group=this.db.prepare('SELECT * FROM facebook_groups WHERE id=? AND workspace=? AND account_id=?').get(post.group_id,workspace,post.account_id);
    if(settings.mode==='SHADOW')fail('当前为影子模式，只扫描和生成候选，不执行写操作');
    if(!group?.enabled||group.membership_status!=='JOINED')fail('群组已停用或尚未确认加入');
    if(!settings.enabled||!settings.global_enabled||!settings.account_enabled||!group.proactive_engagement_enabled)fail('GLOBAL、ACCOUNT 或 GROUP 开关已关闭');
    if(account.session_health!=='HEALTHY')fail('Facebook 登录身份未处于已核验健康状态');
    if(!['CANDIDATE','FACT_VERIFIED','PARTIAL_RETRY'].includes(post.state))fail('帖子当前不可执行；UNKNOWN 必须先核对');
    if(post.fact_status==='REQUIRED'||post.fact_status==='UNVERIFIED')fail('事实敏感回复尚未可靠核验');
    let decision=post.proposed_action;
    if(decision.includes('LIKE')&&!settings.auto_like)decision=decision==='LIKE_AND_REPLY'?'REPLY_ONLY':'SKIP';
    if(decision.includes('REPLY')&&!settings.auto_reply)decision=decision==='LIKE_AND_REPLY'?'LIKE_ONLY':'SKIP';
    if(decision==='SKIP')fail('当前自动开关没有允许的动作');
    if(decision.includes('REPLY')&&!String(replyBody||'').trim())fail('回复动作需要已审核生成的原语言回复文本');
    const existing=this.db.prepare('SELECT * FROM engagement_actions WHERE post_id=?').all(post.id);
    if(existing.some(a=>['ATTEMPTING','RECONCILE_PENDING'].includes(a.state)))fail('已有待核对动作，禁止重试');
    const kinds=(decision==='LIKE_AND_REPLY'?['LIKE','INITIAL_REPLY']:decision==='LIKE_ONLY'?['LIKE']:['INITIAL_REPLY']).filter(kind=>!existing.some(a=>a.action_type===kind&&a.state==='CONFIRMED'));
    if(!kinds.length)fail('这些动作已经完成，不能重复执行');
    const day=new Date().toISOString().slice(0,10),time=new Date().toISOString();
    const previous=this.db.prepare('SELECT * FROM engagement_daily_slots WHERE account_id=? AND group_id=? AND post_id=? AND day=?').get(post.account_id,post.group_id,post.id,day);
    const used=this.db.prepare("SELECT count(*) n FROM engagement_daily_slots WHERE workspace=? AND account_id=? AND group_id=? AND day=? AND state IN ('RESERVED','CONSUMED')").get(workspace,post.account_id,post.group_id,day).n;
    if(used-(previous&&previous.state!=='RELEASED'?1:0)>=settings.daily_limit)fail('该群组今日主动互动额度已用完');
    this.db.prepare("INSERT INTO engagement_daily_slots VALUES(?,?,?,?,?,?,?,?) ON CONFLICT(account_id,group_id,post_id,day) DO UPDATE SET state=CASE WHEN engagement_daily_slots.state='CONSUMED' THEN 'CONSUMED' ELSE 'RESERVED' END,reserved_at=excluded.reserved_at").run(workspace,post.account_id,post.group_id,post.id,day,'RESERVED',time,null);
    const actions=kinds.map(kind=>{
      const old=existing.find(a=>a.action_type===kind);if(old&&old.state!=='FAILED_CONFIRMED_ABSENT')fail('旧动作没有确认未提交');
      const id=old?.id||randomUUID();
      this.interactionBudget?.reserve({workspace,accountId:post.account_id,groupId:post.group_id,author:post.author,target:interactionTarget(post.permalink,post.external_id||post.id),operation:kind==='LIKE'?'LIKE':'REPLY',owner:'proactive:'+id});
      if(old)this.event(workspace,'proactive_retry_confirmed_absent',{action_id:id,old_attempt_id:old.attempt_id});
      this.db.prepare("INSERT INTO engagement_actions VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) ON CONFLICT(account_id,post_id,action_type) DO UPDATE SET state='ATTEMPTING',reply_body=excluded.reply_body,attempt_id=excluded.attempt_id,evidence_json=excluded.evidence_json,error=NULL,updated_at=excluded.updated_at WHERE engagement_actions.state='FAILED_CONFIRMED_ABSENT'").run(id,workspace,post.account_id,post.group_id,post.id,kind,'ATTEMPTING',kind==='INITIAL_REPLY'?replyBody:null,randomUUID(),JSON.stringify({decision}),null,time,time);
      return this.proactiveAction(workspace,id);
    });
    this.db.prepare("UPDATE engagement_posts SET state='ATTEMPTING' WHERE id=?").run(post.id);
    return {decision,actions,slot:this.db.prepare('SELECT * FROM engagement_daily_slots WHERE account_id=? AND group_id=? AND post_id=? AND day=?').get(post.account_id,post.group_id,post.id,day)};
  });}
  failProactiveBeforeSubmit(workspace,postId,reason){return this.tx(()=>{
    const post=this.proactivePost(workspace,postId),actions=this.db.prepare("SELECT * FROM engagement_actions WHERE post_id=? AND state='ATTEMPTING'").all(post.id);
    for(const action of actions){this.interactionBudget?.finish('proactive:'+action.id,'RELEASED');this.db.prepare("UPDATE engagement_actions SET state='FAILED_CONFIRMED_ABSENT',error=?,updated_at=? WHERE id=?").run(reason,new Date().toISOString(),action.id);}
    const completed=this.db.prepare("SELECT 1 FROM engagement_actions WHERE post_id=? AND state='CONFIRMED'").get(post.id);
    this.db.prepare("UPDATE engagement_posts SET state=?,reason=? WHERE id=?").run(completed?'PARTIAL_RETRY':'CANDIDATE',reason,post.id);
    if(!completed)this.db.prepare("UPDATE engagement_daily_slots SET state='RELEASED' WHERE post_id=? AND state='RESERVED'").run(post.id);
    this.event(workspace,'proactive_submit_not_started',{post_id:post.id,reason});return this.proactivePost(workspace,post.id);
  });}

  finishProactiveAction(workspace,actionId,evidence){return this.tx(()=>{const action=this.proactiveAction(workspace,actionId),post=this.proactivePost(workspace,action.post_id);if(action.state!=='ATTEMPTING')fail('动作不在可完成状态');if(!evidence?.readback_verified)fail('缺少独立回读，不能标记成功');const time=new Date().toISOString();this.interactionBudget?.finish('proactive:'+action.id,'CONSUMED');this.db.prepare("UPDATE engagement_actions SET state='CONFIRMED',evidence_json=?,updated_at=? WHERE id=?").run(JSON.stringify(evidence),time,action.id);const confirmed=this.db.prepare("SELECT action_type FROM engagement_actions WHERE post_id=? AND state='CONFIRMED'").all(post.id).map(x=>x.action_type),state=confirmed.includes('LIKE')&&confirmed.includes('INITIAL_REPLY')?'LIKED_AND_REPLIED':confirmed.includes('LIKE')?'LIKED':'REPLIED';this.db.prepare('UPDATE engagement_posts SET state=? WHERE id=?').run(state,post.id);this.db.prepare("UPDATE engagement_daily_slots SET state='CONSUMED',consumed_at=COALESCE(consumed_at,?) WHERE workspace=? AND group_id=? AND post_id=? AND state IN ('RESERVED','CONSUMED')").run(time,workspace,post.group_id,post.id);if(action.action_type==='INITIAL_REPLY')this.db.prepare('INSERT OR IGNORE INTO engagement_threads VALUES(?,?,?,?,?,?,?,?,?,?,?,?)').run(randomUUID(),workspace,post.account_id,post.group_id,post.id,evidence.comment_id||null,0,'ACTIVE',null,time,time,time);this.event(workspace,'proactive_engagement_readback',{action_id:action.id,post_id:post.id,action:action.action_type});return this.proactiveAction(workspace,action.id)});}
  markProactiveUnknown(workspace,actionId,reason){const action=this.proactiveAction(workspace,actionId),time=new Date().toISOString();this.db.prepare("UPDATE engagement_actions SET state='RECONCILE_PENDING',error=?,updated_at=? WHERE id=?").run(reason||'提交结果不明确',time,action.id);this.db.prepare("UPDATE engagement_posts SET state='RECONCILE_PENDING',reason='写操作结果不明确，禁止重试，必须先回读' WHERE id=?").run(action.post_id);const unstarted=this.db.prepare("SELECT id FROM engagement_actions WHERE post_id=? AND id<>? AND state='ATTEMPTING'").all(action.post_id,action.id);for(const sibling of unstarted){this.interactionBudget?.finish('proactive:'+sibling.id,'RELEASED');this.db.prepare("UPDATE engagement_actions SET state='FAILED_CONFIRMED_ABSENT',error='前序动作结果未知，此动作尚未开始' WHERE id=?").run(sibling.id);}this.event(workspace,'proactive_engagement_unknown',{action_id:action.id});return this.proactiveAction(workspace,action.id);}
  reconcileProactiveAction(workspace,actionId,evidence){const action=this.proactiveAction(workspace,actionId);if(action.state!=='RECONCILE_PENDING')fail('动作当前不需要核对');if(evidence?.found)return this.finishReconciledProactive(workspace,action,evidence);if(evidence?.absence_proven!==true)fail('无法证明动作未发生，继续保持待核对');const time=new Date().toISOString();return this.tx(()=>{this.interactionBudget?.finish('proactive:'+action.id,'RELEASED');this.db.prepare("UPDATE engagement_actions SET state='FAILED_CONFIRMED_ABSENT',evidence_json=?,updated_at=? WHERE id=?").run(JSON.stringify(evidence),time,action.id);const remaining=this.db.prepare("SELECT 1 FROM engagement_actions WHERE post_id=? AND state IN ('CONFIRMED','ATTEMPTING','RECONCILE_PENDING') LIMIT 1").get(action.post_id);this.db.prepare("UPDATE engagement_posts SET state=?,reason=? WHERE id=?").run(remaining?(this.db.prepare("SELECT 1 FROM engagement_actions WHERE post_id=? AND state IN ('ATTEMPTING','RECONCILE_PENDING')").get(action.post_id)?'RECONCILE_PENDING':'PARTIAL_RETRY'):'CANDIDATE',remaining?'部分动作已发生或待核对，不能重放整组动作':'独立回读确认动作未发生，可重新审核',action.post_id);if(!remaining)this.db.prepare("UPDATE engagement_daily_slots SET state='RELEASED' WHERE post_id=? AND state='RESERVED'").run(action.post_id);return this.proactiveAction(workspace,action.id)});}
  finishReconciledProactive(workspace,action,evidence){const time=new Date().toISOString(),post=this.proactivePost(workspace,action.post_id),confirmed=this.db.prepare("SELECT action_type FROM engagement_actions WHERE post_id=? AND state='CONFIRMED'").all(post.id).map(x=>x.action_type).concat(action.action_type),state=confirmed.includes('LIKE')&&confirmed.includes('INITIAL_REPLY')?'LIKED_AND_REPLIED':confirmed.includes('LIKE')?'LIKED':'REPLIED';return this.tx(()=>{this.interactionBudget?.finish('proactive:'+action.id,'CONSUMED');this.db.prepare("UPDATE engagement_actions SET state='CONFIRMED',evidence_json=?,updated_at=? WHERE id=?").run(JSON.stringify({...evidence,readback_verified:true,reconciled:true}),time,action.id);const pending=this.db.prepare("SELECT 1 FROM engagement_actions WHERE post_id=? AND state='RECONCILE_PENDING'").get(post.id),unstarted=this.db.prepare("SELECT 1 FROM engagement_actions WHERE post_id=? AND state='FAILED_CONFIRMED_ABSENT'").get(post.id);this.db.prepare('UPDATE engagement_posts SET state=? WHERE id=?').run(pending?'RECONCILE_PENDING':unstarted?'PARTIAL_RETRY':state,post.id);this.db.prepare("UPDATE engagement_daily_slots SET state='CONSUMED',consumed_at=? WHERE post_id=? AND state='RESERVED'").run(time,post.id);return this.proactiveAction(workspace,action.id)});}
  recordThreadMessage(workspace,threadId,input){const thread=this.db.prepare('SELECT * FROM engagement_threads WHERE id=? AND workspace=?').get(threadId,workspace)||fail('互动会话不存在'),settings=this.proactiveSettings(workspace,thread.account_id),body=String(input.body||'').trim();if(!body)fail('消息正文不能为空');if(input.direction==='EXTERNAL'&&isNegativeReply(body)){this.db.prepare("UPDATE engagement_threads SET status='STOPPED_NEGATIVE',last_external_reply_at=?,updated_at=? WHERE id=?").run(input.observed_at||new Date().toISOString(),new Date().toISOString(),thread.id)}const current=this.db.prepare('SELECT * FROM engagement_threads WHERE id=?').get(thread.id);if(input.direction==='OUTBOUND'&&(current.status!=='ACTIVE'||current.followup_count>=settings.max_followups))fail('会话已停止或 follow-up 已达上限');const id=randomUUID(),time=input.observed_at||new Date().toISOString();this.db.prepare('INSERT OR IGNORE INTO engagement_messages VALUES(?,?,?,?,?,?,?,?,?,?,?)').run(id,workspace,thread.id,input.external_id||null,input.parent_external_id||null,input.direction,input.author||null,body,input.language||'en',input.state||'OBSERVED',time);if(input.direction==='OUTBOUND')this.db.prepare('UPDATE engagement_threads SET followup_count=followup_count+1,last_our_reply_at=?,updated_at=? WHERE id=?').run(time,new Date().toISOString(),thread.id);else this.db.prepare('UPDATE engagement_threads SET last_external_reply_at=?,updated_at=? WHERE id=?').run(time,new Date().toISOString(),thread.id);return this.db.prepare('SELECT * FROM engagement_threads WHERE id=?').get(thread.id);}
  proactivePost(workspace,id){return this.db.prepare('SELECT * FROM engagement_posts WHERE id=? AND workspace=?').get(id,workspace)||fail('主动互动帖子不存在');}
  proactiveAction(workspace,id){const row=this.db.prepare('SELECT * FROM engagement_actions WHERE id=? AND workspace=?').get(id,workspace)||fail('主动互动动作不存在');return {...row,evidence:JSON.parse(row.evidence_json)};}
  account(workspace,id){return this.db.prepare('SELECT * FROM facebook_accounts WHERE id=? AND workspace=? AND enabled=1').get(id,workspace)||fail('Facebook 账号不属于当前客户或已停用');}
  job(workspace,id){return this.db.prepare('SELECT * FROM group_jobs WHERE id=? AND workspace=?').get(id,workspace)||fail('群组任务不属于当前客户');}
  command(workspace,kind,id,action,input={}){if(!workspace)fail('请先进入客户，Agency 不能执行');return this.tx(()=>{
    const x=this.get(kind,id,workspace);
    if(kind==='content'&&action==='revise'){
      const body=String(input.body??'').trim();if(!body)fail('正文不能为空');
      const revision=randomUUID();this.db.prepare('INSERT INTO revisions VALUES(?,?,?,?,?)').run(revision,id,workspace,body,hash(body));x.body=body;x.revision=revision;x.hash=hash(body);this.put(kind,x);
      for(const t of this.list('tasks',workspace).filter(t=>t.contentId===id&&!['PUBLISHED','REPLIED','DRAFT_WRITTEN'].includes(t.state))){t.revisionValid=false;t.approved=false;this.put('tasks',t);}
    } else if(kind==='comments'&&action==='reply'){
      if(!input.body?.trim())fail('回复不能为空');if(x.intent==='RISK_QUESTION')fail('具体风险问题需人工审核');
      if(this.list('tasks',workspace).some(t=>t.commentId===id))fail('该评论已有回复任务');
      this.put('tasks',{id:randomUUID(),workspaceId:workspace,commentId:id,body:input.body,platform:'Facebook Group',state:'READY',identityOk:true,executionProfileOk:true,revisionValid:true,approved:false,version:1});x.state='REPLY_DRAFTED';this.put(kind,x);
    } else if(kind==='tasks'){
      if(input.version!==x.version)fail('任务版本已变化，请刷新');
      const c=x.contentId?this.get('content',x.contentId,workspace):null;
      if(action==='approve'){
        if(!['READY','NEEDS_REVIEW'].includes(x.state))fail('当前状态不能重新审批');x.approved=true;x.revisionValid=true;x.scope=hash([c?.hash,x.body,x.platform,workspace]);x.state='READY';
      }else if(action==='prepare'){
        if(x.state!=='READY')fail('任务已执行或待核对，不能重复准备');
        if(!x.identityOk||!x.executionProfileOk)fail('身份或执行环境不匹配，写入前阻止');
        if(!x.approved||!x.revisionValid||x.scope!==hash([c?.hash,x.body,x.platform,workspace]))fail('请审核当前内容版本');
        if(this.list('tasks',workspace).some(t=>t.id!==id&&['COMPOSER_READY','SUBMITTED','UNKNOWN'].includes(t.state)))fail('当前客户执行环境被占用，请先处理活动任务');
        x.attempt=randomUUID();this.db.prepare('INSERT INTO attempts VALUES(?,?,?,?,?)').run(x.attempt,id,workspace,x.scope,'PREPARED');x.state='COMPOSER_READY';
      }else if(action==='submit'){
        if(x.state!=='COMPOSER_READY'||!x.revisionValid)fail('必须先完成有效预检');
        this.db.prepare("UPDATE attempts SET phase='SUBMITTED' WHERE id=?").run(x.attempt);x.state='SUBMITTED';
        // Mock adapter stores independent evidence; caller cannot supply a success boolean.
        if(input.simulate!=='unknown')this.db.prepare('INSERT OR REPLACE INTO receipts VALUES(?,?,?,?)').run(id,workspace,x.scope,x.commentId?'REPLIED':x.platform==='公众号'?'DRAFT_WRITTEN':'PUBLISHED');
      }else if(action==='reconcile'){
        if(!['SUBMITTED','UNKNOWN'].includes(x.state))fail('当前状态不能对账');const r=this.db.prepare('SELECT * FROM receipts WHERE task=? AND workspace=?').get(id,workspace);
        x.state=r&&r.hash===x.scope?r.outcome:'UNKNOWN';x.reason=x.state==='UNKNOWN'?'没有足够证据；禁止重新提交':'模拟平台独立回执已核对';
        this.db.prepare('UPDATE attempts SET phase=? WHERE id=?').run(x.state,x.attempt);
      }else if(action==='cancel'){
        if(!['READY','COMPOSER_READY','NEEDS_REVIEW'].includes(x.state))fail('可能已提交，不能取消');x.state='SKIPPED';
      }else fail('不支持的任务操作');
      x.version++;this.put(kind,x);
    }else fail('不支持的操作');
    this.event(workspace,action,{kind,id,state:x.state,revision:x.revision});return x;
  });}
  close(){this.db.close();}
}
function normalizeFacebookUrl(value){const u=new URL(String(value));if(!/(^|\.)facebook\.com$/.test(u.hostname))fail('必须使用 Facebook 链接');u.protocol='https:';u.hash='';return u.toString();}
function normalizeGroupUrl(value){const u=new URL(normalizeFacebookUrl(value));if(!/\/(groups\/[^/?#]+|share\/g\/[^/?#]+)/.test(u.pathname))fail('请输入 Facebook 群组链接');u.search='';return u.toString().replace(/\/$/,'');}
function groupId(url){return new URL(url).pathname.match(/\/groups\/([^/]+)/)?.[1]||null;}
function localConfigUrl(value){const text=String(value||'').trim();if(!text)return null;if(/^[a-z][a-z0-9+.-]*:/i.test(text)&&!text.startsWith('file://'))fail('账号配置只允许本地文件地址');if(/\.(rtf|docx?)$/i.test(text))fail('富文本不能作为账号配置；请选择纯文本 .env 或 .json 文件');return text;}
function splitTerms(value){return [...new Set((Array.isArray(value)?value:String(value||'').split(/[,，\n]/)).map(x=>String(x).trim()).filter(Boolean))].slice(0,50);}
function bounded(value,min,max,fallback){const n=Number(value);return Number.isInteger(n)?Math.min(max,Math.max(min,n)):fallback;}
function classifyComment(body,policy){const text=String(body||''),excluded=policy.excluded.find(x=>text.toLowerCase().includes(x.toLowerCase())),topic=policy.topics.find(x=>text.toLowerCase().includes(x.toLowerCase()));if(excluded)return {topic:null,risk:'BLOCKED',state:'SKIP',reason:`命中排除词：${excluded}`};if(!topic)return {topic:null,risk:'LOW',state:'SKIP',reason:'没有命中配置主题'};if(/律师|法律|劳动法|劳动争议|违法|税|处罚|赔偿|解雇|合同|签证|政策|政府|政治|价格|报价|投诉|隐私|身份证|电话/i.test(text))return {topic,risk:'HIGH',state:'HUMAN_REVIEW',reason:'涉及法律、税务、政策、承诺或个人信息'};if(!/[?？]|请问|怎么|如何|为什么|是否|能不能|有没有/.test(text))return {topic,risk:'LOW',state:'SKIP',reason:'不是明确的问题或求助'};return {topic,risk:'LOW',state:'REPLY_CANDIDATE',reason:'命中主题且属于低风险明确问题'};}
function draftReply(body,classified){if(classified.state!=='REPLY_CANDIDATE')return null;const topic=classified.topic||'这个问题';if(/怎么|如何/.test(body))return `${topic}要结合具体场景判断。方便补充一下所在城市、行业和目前卡在哪一步吗？`;return `这个情况需要结合实际条件看。方便补充一下行业、所在地和目前遇到的具体问题吗？`;}
